import type { Category, Conversation, Translation } from "./schema"

export const MY_PHRASES_ID = "my-phrases"

export const CATEGORY_GROUPS = [
  { id: "food", label: "🍜 Food & Drink" },
  { id: "shopping", label: "🛍️ Shopping" },
  { id: "travel", label: "🚆 Travel" },
  { id: "conversation", label: "💬 Conversation" },
  { id: "safety", label: "🆘 Emergencies" },
  { id: "basics", label: "📖 Basics" },
  { id: "work", label: "💼 Work" },
  { id: "study", label: "📚 JLPT Study" },
  { id: "slang", label: "😎 Slang" },
] as const

export const categories: Category[] = [
  {
    id: "cat1",
    name: "Convenience Store",
    description: "Common phrases used in convenience stores.",
    group: "shopping",
  },
  {
    id: "cat2",
    name: "Restaurant",
    description: "Common phrases used in restaurants.",
    group: "food",
  },
  {
    id: "cat3",
    name: "Shop",
    description: "Common phrases used in shops.",
    group: "shopping",
  },
  {
    id: "cat4",
    name: "Transportation",
    description:
      "Common phrases used at train stations, in taxis, and at bus stops.",
    group: "travel",
  },
  {
    id: "cat5",
    name: "Hotel",
    description: "Common phrases used at hotels.",
    group: "travel",
  },
  {
    id: "cat6",
    name: "Airport",
    description: "Common phrases used at airports.",
    group: "travel",
  },
  {
    id: "cat7",
    name: "Sightseeing",
    description: "Common phrases used while sightseeing.",
    group: "travel",
  },
  {
    id: "cat8",
    name: "Everyday Conversation",
    description: "Common phrases used in everyday conversation.",
    group: "conversation",
  },
  {
    id: "cat9",
    name: "Emergencies",
    description: "Common phrases used during emergencies.",
    group: "safety",
  },
  {
    id: "cat10",
    name: "Animal Vocabulary (Doubutsu)",
    description: "Japanese words for common animals.",
    group: "basics",
  },
  {
    id: "cat11",
    name: "Self-introduction",
    description: "Phrases used when introducing yourself.",
    group: "conversation",
  },
  {
    id: "cat12",
    name: "Starting a New Job",
    description: "Phrases used when starting a new job.",
    group: "work",
  },
  {
    id: "cat13",
    name: "Making a Purchase",
    description: "Phrases used when making a purchase.",
    group: "shopping",
  },
  {
    id: "cat14",
    name: "Asking Business Hours",
    description: "Phrases used when asking about business hours.",
    group: "shopping",
  },
  {
    id: "cat15",
    name: "Confirming a Destination",
    description: "Phrases used when confirming a destination.",
    group: "travel",
  },
  {
    id: "cat16",
    name: "JLPT N5",
    description: "Essential expressions and patterns for the JLPT N5 level.",
    group: "study",
  },
  {
    id: "cat17",
    name: "JLPT N4",
    description: "Essential expressions and patterns for the JLPT N4 level.",
    group: "study",
  },
  {
    id: "cat18",
    name: "JLPT N3",
    description: "Essential expressions and patterns for the JLPT N3 level.",
    group: "study",
  },
  {
    id: "cat19",
    name: "Casual Slang",
    description: "Common Japanese slang and casual expressions.",
    group: "slang",
  },
]

export const conversations: Conversation[] = [
  // =========================================================
  // Convenience Store
  // =========================================================
  {
    id: "conv1",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Excuse me, where can I find the snacks?",
    timestamp: "2023-10-01T10:00:00Z",
  },
  {
    id: "conv2",
    category_id: "cat1",
    context: "At a convenience store",
    content: "How much is this drink?",
    timestamp: "2023-10-01T10:05:00Z",
  },
  {
    id: "conv7",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Where is the restroom?",
    timestamp: "2023-10-01T10:10:00Z",
  },
  {
    id: "conv9",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Can I pay by credit card?",
    timestamp: "2023-10-01T10:15:00Z",
  },
  {
    id: "conv10",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Do you have a plastic bag?",
    timestamp: "2023-10-01T10:20:00Z",
  },
  {
    id: "conv11",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Can I heat this up?",
    timestamp: "2023-10-01T10:25:00Z",
  },
  {
    id: "conv12",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Do you sell SIM cards here?",
    timestamp: "2023-10-01T10:30:00Z",
  },
  {
    id: "conv13",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Can I use the ATM?",
    timestamp: "2023-10-01T10:35:00Z",
  },
  {
    id: "conv14",
    category_id: "cat1",
    context: "At a convenience store",
    content: "Do you accept cashless payments?",
    timestamp: "2023-10-01T10:40:00Z",
  },

  // =========================================================
  // Restaurant
  // =========================================================
  {
    id: "conv3",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Can I see the menu, please?",
    timestamp: "2023-10-01T11:00:00Z",
  },
  {
    id: "conv4",
    category_id: "cat2",
    context: "At a restaurant",
    content: "I would like to order sushi.",
    timestamp: "2023-10-01T11:05:00Z",
  },
  {
    id: "conv8",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Can I get the bill, please?",
    timestamp: "2023-10-01T11:10:00Z",
  },
  {
    id: "conv15",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Do you have a table for two?",
    timestamp: "2023-10-01T11:15:00Z",
  },
  {
    id: "conv16",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Do I need to make a reservation?",
    timestamp: "2023-10-01T11:20:00Z",
  },
  {
    id: "conv17",
    category_id: "cat2",
    context: "At a restaurant",
    content: "What do you recommend?",
    timestamp: "2023-10-01T11:25:00Z",
  },
  {
    id: "conv18",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Is this dish spicy?",
    timestamp: "2023-10-01T11:30:00Z",
  },
  {
    id: "conv19",
    category_id: "cat2",
    context: "At a restaurant",
    content: "I don't eat pig's meat.",
    timestamp: "2023-10-01T11:35:00Z",
  },
  {
    id: "conv20",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Can I have some water, please?",
    timestamp: "2023-10-01T11:40:00Z",
  },
  {
    id: "conv21",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Can we pay separately?",
    timestamp: "2023-10-01T11:45:00Z",
  },
  {
    id: "conv22",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Is service included?",
    timestamp: "2023-10-01T11:50:00Z",
  },

  // =========================================================
  // Shopping
  // =========================================================
  {
    id: "conv5",
    category_id: "cat3",
    context: "At a shop",
    content: "Do you have this in a larger size?",
    timestamp: "2023-10-01T12:00:00Z",
  },
  {
    id: "conv6",
    category_id: "cat3",
    context: "At a shop",
    content: "Can I try this on?",
    timestamp: "2023-10-01T12:05:00Z",
  },
  {
    id: "conv23",
    category_id: "cat3",
    context: "At a shop",
    content: "Do you have this in another color?",
    timestamp: "2023-10-01T12:10:00Z",
  },
  {
    id: "conv24",
    category_id: "cat3",
    context: "At a shop",
    content: "How much does this cost?",
    timestamp: "2023-10-01T12:15:00Z",
  },
  {
    id: "conv25",
    category_id: "cat3",
    context: "At a shop",
    content: "Is this on sale?",
    timestamp: "2023-10-01T12:20:00Z",
  },
  {
    id: "conv26",
    category_id: "cat3",
    context: "At a shop",
    content: "Do you have a smaller size?",
    timestamp: "2023-10-01T12:25:00Z",
  },
  {
    id: "conv27",
    category_id: "cat3",
    context: "At a shop",
    content: "Can I pay with a credit card?",
    timestamp: "2023-10-01T12:30:00Z",
  },
  {
    id: "conv28",
    category_id: "cat3",
    context: "At a shop",
    content: "Can I get a tax refund?",
    timestamp: "2023-10-01T12:35:00Z",
  },
  {
    id: "conv29",
    category_id: "cat3",
    context: "At a shop",
    content: "Where is the fitting room?",
    timestamp: "2023-10-01T12:40:00Z",
  },
  {
    id: "conv30",
    category_id: "cat3",
    context: "At a shop",
    content: "Can I return this?",
    timestamp: "2023-10-01T12:45:00Z",
  },

  // =========================================================
  // Train / Transportation
  // =========================================================
  {
    id: "conv31",
    category_id: "cat4",
    context: "At a train station",
    content: "Where is the ticket machine?",
    timestamp: "2023-10-01T13:00:00Z",
  },
  {
    id: "conv32",
    category_id: "cat4",
    context: "At a train station",
    content: "Which train goes to Tokyo?",
    timestamp: "2023-10-01T13:05:00Z",
  },
  {
    id: "conv33",
    category_id: "cat4",
    context: "At a train station",
    content: "Which platform should I go to?",
    timestamp: "2023-10-01T13:10:00Z",
  },
  {
    id: "conv34",
    category_id: "cat4",
    context: "At a train station",
    content: "How much is a ticket to Kyoto?",
    timestamp: "2023-10-01T13:15:00Z",
  },
  {
    id: "conv35",
    category_id: "cat4",
    context: "At a train station",
    content: "Is this train bound for Osaka?",
    timestamp: "2023-10-01T13:20:00Z",
  },
  {
    id: "conv36",
    category_id: "cat4",
    context: "At a train station",
    content: "Where can I recharge my IC card?",
    timestamp: "2023-10-01T13:25:00Z",
  },
  {
    id: "conv37",
    category_id: "cat4",
    context: "At a train station",
    content: "When is the next train?",
    timestamp: "2023-10-01T13:30:00Z",
  },
  {
    id: "conv38",
    category_id: "cat4",
    context: "In a taxi",
    content: "Please take me to this address.",
    timestamp: "2023-10-01T13:35:00Z",
  },
  {
    id: "conv39",
    category_id: "cat4",
    context: "In a taxi",
    content: "How much will it cost?",
    timestamp: "2023-10-01T13:40:00Z",
  },
  {
    id: "conv40",
    category_id: "cat4",
    context: "At a bus stop",
    content: "Does this bus go to the station?",
    timestamp: "2023-10-01T13:45:00Z",
  },

  // =========================================================
  // Hotel
  // =========================================================
  {
    id: "conv41",
    category_id: "cat5",
    context: "At a hotel",
    content: "I have a reservation.",
    timestamp: "2023-10-01T14:00:00Z",
  },
  {
    id: "conv42",
    category_id: "cat5",
    context: "At a hotel",
    content: "I'd like to check in.",
    timestamp: "2023-10-01T14:05:00Z",
  },
  {
    id: "conv43",
    category_id: "cat5",
    context: "At a hotel",
    content: "What time is check-out?",
    timestamp: "2023-10-01T14:10:00Z",
  },
  {
    id: "conv44",
    category_id: "cat5",
    context: "At a hotel",
    content: "Is breakfast included?",
    timestamp: "2023-10-01T14:15:00Z",
  },
  {
    id: "conv45",
    category_id: "cat5",
    context: "At a hotel",
    content: "Can I leave my luggage here?",
    timestamp: "2023-10-01T14:20:00Z",
  },
  {
    id: "conv46",
    category_id: "cat5",
    context: "At a hotel",
    content: "Could you call a taxi for me?",
    timestamp: "2023-10-01T14:25:00Z",
  },
  {
    id: "conv47",
    category_id: "cat5",
    context: "At a hotel",
    content: "Is there Wi-Fi in the room?",
    timestamp: "2023-10-01T14:30:00Z",
  },
  {
    id: "conv48",
    category_id: "cat5",
    context: "At a hotel",
    content: "Could I get another towel?",
    timestamp: "2023-10-01T14:35:00Z",
  },

  // =========================================================
  // Airport
  // =========================================================
  {
    id: "conv49",
    category_id: "cat6",
    context: "At an airport",
    content: "Where is the check-in counter?",
    timestamp: "2023-10-01T15:00:00Z",
  },
  {
    id: "conv50",
    category_id: "cat6",
    context: "At an airport",
    content: "Where is the baggage claim?",
    timestamp: "2023-10-01T15:05:00Z",
  },
  {
    id: "conv51",
    category_id: "cat6",
    context: "At an airport",
    content: "Where is the departure gate?",
    timestamp: "2023-10-01T15:10:00Z",
  },
  {
    id: "conv52",
    category_id: "cat6",
    context: "At an airport",
    content: "How many bags can I check in?",
    timestamp: "2023-10-01T15:15:00Z",
  },
  {
    id: "conv53",
    category_id: "cat6",
    context: "At an airport",
    content: "Where can I exchange money?",
    timestamp: "2023-10-01T15:20:00Z",
  },
  {
    id: "conv54",
    category_id: "cat6",
    context: "At an airport",
    content: "Where can I buy a SIM card?",
    timestamp: "2023-10-01T15:25:00Z",
  },

  // =========================================================
  // Sightseeing
  // =========================================================
  {
    id: "conv55",
    category_id: "cat7",
    context: "While sightseeing",
    content: "How do I get to this place?",
    timestamp: "2023-10-01T16:00:00Z",
  },
  {
    id: "conv56",
    category_id: "cat7",
    context: "While sightseeing",
    content: "How much is the entrance fee?",
    timestamp: "2023-10-01T16:05:00Z",
  },
  {
    id: "conv57",
    category_id: "cat7",
    context: "While sightseeing",
    content: "What time does it open?",
    timestamp: "2023-10-01T16:10:00Z",
  },
  {
    id: "conv58",
    category_id: "cat7",
    context: "While sightseeing",
    content: "Can I take photos here?",
    timestamp: "2023-10-01T16:15:00Z",
  },
  {
    id: "conv59",
    category_id: "cat7",
    context: "While sightseeing",
    content: "Is there a famous place nearby?",
    timestamp: "2023-10-01T16:20:00Z",
  },
  {
    id: "conv60",
    category_id: "cat7",
    context: "While sightseeing",
    content: "Could you take a photo for us?",
    timestamp: "2023-10-01T16:25:00Z",
  },

  // =========================================================
  // Everyday Conversation
  // =========================================================
  {
    id: "conv61",
    category_id: "cat8",
    context: "Meeting someone",
    content: "Nice to meet you.",
    timestamp: "2023-10-01T17:00:00Z",
  },
  {
    id: "conv62",
    category_id: "cat8",
    context: "Meeting someone",
    content: "Where are you from?",
    timestamp: "2023-10-01T17:05:00Z",
  },
  {
    id: "conv63",
    category_id: "cat8",
    context: "Everyday conversation",
    content: "Do you speak English?",
    timestamp: "2023-10-01T17:10:00Z",
  },
  {
    id: "conv64",
    category_id: "cat8",
    context: "Everyday conversation",
    content: "Could you speak more slowly?",
    timestamp: "2023-10-01T17:15:00Z",
  },
  {
    id: "conv65",
    category_id: "cat8",
    context: "Everyday conversation",
    content: "Could you say that again?",
    timestamp: "2023-10-01T17:20:00Z",
  },
  {
    id: "conv66",
    category_id: "cat8",
    context: "Everyday conversation",
    content: "I don't understand.",
    timestamp: "2023-10-01T17:25:00Z",
  },
  {
    id: "conv67",
    category_id: "cat8",
    context: "Everyday conversation",
    content: "Thank you for your help.",
    timestamp: "2023-10-01T17:30:00Z",
  },
  {
    id: "conv68",
    category_id: "cat8",
    context: "Everyday conversation",
    content: "Excuse me.",
    timestamp: "2023-10-01T17:35:00Z",
  },

  // =========================================================
  // Emergencies
  // =========================================================
  {
    id: "conv69",
    category_id: "cat9",
    context: "During an emergency",
    content: "Please help me.",
    timestamp: "2023-10-01T18:00:00Z",
  },
  {
    id: "conv70",
    category_id: "cat9",
    context: "During an emergency",
    content: "Where is the nearest hospital?",
    timestamp: "2023-10-01T18:05:00Z",
  },
  {
    id: "conv71",
    category_id: "cat9",
    context: "During an emergency",
    content: "I lost my wallet.",
    timestamp: "2023-10-01T18:10:00Z",
  },
  {
    id: "conv72",
    category_id: "cat9",
    context: "During an emergency",
    content: "I lost my passport.",
    timestamp: "2023-10-01T18:15:00Z",
  },
  {
    id: "conv73",
    category_id: "cat9",
    context: "At a police station",
    content: "I need to report something.",
    timestamp: "2023-10-01T18:20:00Z",
  },

  // =========================================================
  // Animal Vocabulary (Doubutsu)
  // =========================================================
  {
    id: "conv74",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Dog",
    timestamp: "2023-10-01T19:00:00Z",
  },
  {
    id: "conv75",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Horse",
    timestamp: "2023-10-01T19:05:00Z",
  },
  {
    id: "conv76",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Bear",
    timestamp: "2023-10-01T19:10:00Z",
  },
  {
    id: "conv77",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Elephant",
    timestamp: "2023-10-01T19:15:00Z",
  },
  {
    id: "conv78",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Rhinoceros",
    timestamp: "2023-10-01T19:20:00Z",
  },
  {
    id: "conv79",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Cat",
    timestamp: "2023-10-01T19:25:00Z",
  },
  {
    id: "conv80",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Cow",
    timestamp: "2023-10-01T19:30:00Z",
  },
  {
    id: "conv81",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Deer",
    timestamp: "2023-10-01T19:35:00Z",
  },
  {
    id: "conv82",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Hippopotamus",
    timestamp: "2023-10-01T19:40:00Z",
  },
  {
    id: "conv83",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Goat",
    timestamp: "2023-10-01T19:45:00Z",
  },
  {
    id: "conv84",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Pig",
    timestamp: "2023-10-01T19:50:00Z",
  },
  {
    id: "conv85",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Donkey",
    timestamp: "2023-10-01T19:55:00Z",
  },
  {
    id: "conv86",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Tiger",
    timestamp: "2023-10-01T20:00:00Z",
  },
  {
    id: "conv87",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Squirrel",
    timestamp: "2023-10-01T20:05:00Z",
  },
  {
    id: "conv88",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Turtle",
    timestamp: "2023-10-01T20:10:00Z",
  },
  {
    id: "conv89",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Leopard",
    timestamp: "2023-10-01T20:15:00Z",
  },
  {
    id: "conv90",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Monkey",
    timestamp: "2023-10-01T20:20:00Z",
  },
  {
    id: "conv91",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Squid",
    timestamp: "2023-10-01T20:25:00Z",
  },
  {
    id: "conv92",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Shark",
    timestamp: "2023-10-01T20:30:00Z",
  },
  {
    id: "conv93",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Snake",
    timestamp: "2023-10-01T20:35:00Z",
  },
  {
    id: "conv94",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Crocodile",
    timestamp: "2023-10-01T20:40:00Z",
  },
  {
    id: "conv95",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Octopus",
    timestamp: "2023-10-01T20:45:00Z",
  },
  {
    id: "conv96",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Crab",
    timestamp: "2023-10-01T20:50:00Z",
  },
  {
    id: "conv97",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Ant",
    timestamp: "2023-10-01T20:55:00Z",
  },
  {
    id: "conv98",
    category_id: "cat10",
    context: "Animal vocabulary (Doubutsu)",
    content: "Crane (bird)",
    timestamp: "2023-10-01T21:00:00Z",
  },

  // =========================================================
  // Self-introduction
  // =========================================================
  {
    id: "conv99",
    category_id: "cat11",
    context: "Self-introduction",
    content: "My name is Andi.",
    timestamp: "2023-10-01T21:05:00Z",
  },
  {
    id: "conv100",
    category_id: "cat11",
    context: "Self-introduction",
    content: "I am Indonesian.",
    timestamp: "2023-10-01T21:10:00Z",
  },
  {
    id: "conv101",
    category_id: "cat11",
    context: "Self-introduction",
    content: "I came from Jakarta.",
    timestamp: "2023-10-01T21:15:00Z",
  },
  {
    id: "conv102",
    category_id: "cat11",
    context: "Self-introduction",
    content: "I look forward to working with you.",
    timestamp: "2023-10-01T21:20:00Z",
  },
  {
    id: "conv103",
    category_id: "cat11",
    context: "Self-introduction",
    content: "This is Mr. Tanaka.",
    timestamp: "2023-10-01T21:25:00Z",
  },
  {
    id: "conv104",
    category_id: "cat11",
    context: "Self-introduction",
    content: "What is your job?",
    timestamp: "2023-10-01T21:30:00Z",
  },

  // =========================================================
  // Starting a New Job
  // =========================================================
  {
    id: "conv105",
    category_id: "cat12",
    context: "Starting a new job",
    content: "Thank you for your continued support.",
    timestamp: "2023-10-01T21:35:00Z",
  },
  {
    id: "conv106",
    category_id: "cat12",
    context: "Starting a new job",
    content: "Here is my business card.",
    timestamp: "2023-10-01T21:40:00Z",
  },
  {
    id: "conv107",
    category_id: "cat12",
    context: "Starting a new job",
    content: "I will do my best.",
    timestamp: "2023-10-01T21:45:00Z",
  },
  {
    id: "conv108",
    category_id: "cat12",
    context: "Starting a new job",
    content: "I am new here.",
    timestamp: "2023-10-01T21:50:00Z",
  },
  {
    id: "conv109",
    category_id: "cat12",
    context: "Starting a new job",
    content: "Please teach me.",
    timestamp: "2023-10-01T21:55:00Z",
  },
  {
    id: "conv110",
    category_id: "cat12",
    context: "Starting a new job",
    content: "Where is my desk?",
    timestamp: "2023-10-01T22:00:00Z",
  },

  // =========================================================
  // Making a Purchase
  // =========================================================
  {
    id: "conv111",
    category_id: "cat13",
    context: "Making a purchase",
    content: "I'll take this, please.",
    timestamp: "2023-10-01T22:05:00Z",
  },
  {
    id: "conv112",
    category_id: "cat13",
    context: "Making a purchase",
    content: "How much is this?",
    timestamp: "2023-10-01T22:10:00Z",
  },
  {
    id: "conv113",
    category_id: "cat13",
    context: "Making a purchase",
    content: "Please give me two of these.",
    timestamp: "2023-10-01T22:15:00Z",
  },
  {
    id: "conv114",
    category_id: "cat13",
    context: "Making a purchase",
    content: "Do you have a bigger one?",
    timestamp: "2023-10-01T22:20:00Z",
  },
  {
    id: "conv115",
    category_id: "cat13",
    context: "Making a purchase",
    content: "I'll take that one over there.",
    timestamp: "2023-10-01T22:25:00Z",
  },
  {
    id: "conv116",
    category_id: "cat13",
    context: "Making a purchase",
    content: "Can I get a receipt?",
    timestamp: "2023-10-01T22:30:00Z",
  },

  // =========================================================
  // Asking Business Hours
  // =========================================================
  {
    id: "conv117",
    category_id: "cat14",
    context: "Asking business hours",
    content: "Until what time are you open?",
    timestamp: "2023-10-01T22:35:00Z",
  },
  {
    id: "conv118",
    category_id: "cat14",
    context: "Asking business hours",
    content: "What time do you open?",
    timestamp: "2023-10-01T22:40:00Z",
  },
  {
    id: "conv119",
    category_id: "cat14",
    context: "Asking business hours",
    content: "What time do you close?",
    timestamp: "2023-10-01T22:45:00Z",
  },
  {
    id: "conv120",
    category_id: "cat14",
    context: "Asking business hours",
    content: "Are you open on Sundays?",
    timestamp: "2023-10-01T22:50:00Z",
  },
  {
    id: "conv121",
    category_id: "cat14",
    context: "Asking business hours",
    content: "Are you open right now?",
    timestamp: "2023-10-01T22:55:00Z",
  },
  {
    id: "conv122",
    category_id: "cat14",
    context: "Asking business hours",
    content: "Are you open on public holidays?",
    timestamp: "2023-10-01T23:00:00Z",
  },

  // =========================================================
  // Confirming a Destination
  // =========================================================
  {
    id: "conv123",
    category_id: "cat15",
    context: "Confirming a destination",
    content: "Does this train go to Shinjuku?",
    timestamp: "2023-10-01T23:05:00Z",
  },
  {
    id: "conv124",
    category_id: "cat15",
    context: "Confirming a destination",
    content: "Does this go to the airport?",
    timestamp: "2023-10-01T23:10:00Z",
  },
  {
    id: "conv125",
    category_id: "cat15",
    context: "Confirming a destination",
    content: "Which platform is for Kyoto?",
    timestamp: "2023-10-01T23:15:00Z",
  },
  {
    id: "conv126",
    category_id: "cat15",
    context: "Confirming a destination",
    content: "How long does it take to get there?",
    timestamp: "2023-10-01T23:20:00Z",
  },
  {
    id: "conv127",
    category_id: "cat15",
    context: "Confirming a destination",
    content: "Please tell me when we arrive.",
    timestamp: "2023-10-01T23:25:00Z",
  },
  {
    id: "conv128",
    category_id: "cat15",
    context: "Confirming a destination",
    content: "Is this the right bus for the museum?",
    timestamp: "2023-10-01T23:30:00Z",
  },

  // =========================================================
  // JLPT N5
  // =========================================================
  {
    id: "conv129",
    category_id: "cat16",
    context: "JLPT N5 - core sentence",
    content: "I am a student.",
    timestamp: "2023-10-02T09:00:00Z",
  },
  {
    id: "conv130",
    category_id: "cat16",
    context: "JLPT N5 - core sentence",
    content: "This is a book.",
    timestamp: "2023-10-02T09:05:00Z",
  },
  {
    id: "conv131",
    category_id: "cat16",
    context: "JLPT N5 - negative",
    content: "This is not a pen.",
    timestamp: "2023-10-02T09:10:00Z",
  },
  {
    id: "conv132",
    category_id: "cat16",
    context: "JLPT N5 - question",
    content: "What is this?",
    timestamp: "2023-10-02T09:15:00Z",
  },
  {
    id: "conv133",
    category_id: "cat16",
    context: "JLPT N5 - time",
    content: "What time is it now?",
    timestamp: "2023-10-02T09:20:00Z",
  },
  {
    id: "conv134",
    category_id: "cat16",
    context: "JLPT N5 - verb",
    content: "I go to school every day.",
    timestamp: "2023-10-02T09:25:00Z",
  },
  {
    id: "conv135",
    category_id: "cat16",
    context: "JLPT N5 - te form request",
    content: "Please open the window.",
    timestamp: "2023-10-02T09:30:00Z",
  },
  {
    id: "conv136",
    category_id: "cat16",
    context: "JLPT N5 - permission",
    content: "May I sit here?",
    timestamp: "2023-10-02T09:35:00Z",
  },
  {
    id: "conv137",
    category_id: "cat16",
    context: "JLPT N5 - desire",
    content: "I want to go to Japan.",
    timestamp: "2023-10-02T09:40:00Z",
  },
  {
    id: "conv138",
    category_id: "cat16",
    context: "JLPT N5 - existence",
    content: "There is a book on the desk.",
    timestamp: "2023-10-02T09:45:00Z",
  },
  {
    id: "conv139",
    category_id: "cat16",
    context: "JLPT N5 - existence",
    content: "There is a cat in the garden.",
    timestamp: "2023-10-02T09:50:00Z",
  },
  {
    id: "conv140",
    category_id: "cat16",
    context: "JLPT N5 - like/dislike",
    content: "I like music.",
    timestamp: "2023-10-02T09:55:00Z",
  },
  {
    id: "conv141",
    category_id: "cat16",
    context: "JLPT N5 - ability",
    content: "I can swim.",
    timestamp: "2023-10-02T10:00:00Z",
  },
  {
    id: "conv142",
    category_id: "cat16",
    context: "JLPT N5 - comparison",
    content: "Tokyo is more crowded than Osaka.",
    timestamp: "2023-10-02T10:05:00Z",
  },
  {
    id: "conv143",
    category_id: "cat16",
    context: "JLPT N5 - from now on",
    content: "From now on, I will study harder.",
    timestamp: "2023-10-02T10:10:00Z",
  },
  {
    id: "conv144",
    category_id: "cat16",
    context: "JLPT N5 - request",
    content: "Please say it one more time.",
    timestamp: "2023-10-02T10:15:00Z",
  },
  {
    id: "conv145",
    category_id: "cat16",
    context: "JLPT N5 - past tense",
    content: "I ate breakfast at seven.",
    timestamp: "2023-10-02T10:20:00Z",
  },
  {
    id: "conv146",
    category_id: "cat16",
    context: "JLPT N5 - progressive",
    content: "I am eating now.",
    timestamp: "2023-10-02T10:25:00Z",
  },
  {
    id: "conv147",
    category_id: "cat16",
    context: "JLPT N5 - prohibition",
    content: "Please don't smoke here.",
    timestamp: "2023-10-02T10:30:00Z",
  },
  {
    id: "conv148",
    category_id: "cat16",
    context: "JLPT N5 - price",
    content: "How much is this?",
    timestamp: "2023-10-02T10:35:00Z",
  },
  {
    id: "conv149",
    category_id: "cat16",
    context: "JLPT N5 - question word",
    content: "Who is that person?",
    timestamp: "2023-10-02T10:40:00Z",
  },
  {
    id: "conv150",
    category_id: "cat16",
    context: "JLPT N5 - question word",
    content: "When are you going to Japan?",
    timestamp: "2023-10-02T10:45:00Z",
  },
  {
    id: "conv151",
    category_id: "cat16",
    context: "JLPT N5 - means",
    content: "I came to Japan by plane.",
    timestamp: "2023-10-02T10:50:00Z",
  },
  {
    id: "conv152",
    category_id: "cat16",
    context: "JLPT N5 - duration",
    content: "I have lived here for three years.",
    timestamp: "2023-10-02T10:55:00Z",
  },
  {
    id: "conv153",
    category_id: "cat16",
    context: "JLPT N5 - sentence ending",
    content: "It's cold today, isn't it?",
    timestamp: "2023-10-02T11:00:00Z",
  },
  {
    id: "conv154",
    category_id: "cat16",
    context: "JLPT N5 - offering",
    content: "Would you like some coffee?",
    timestamp: "2023-10-02T11:05:00Z",
  },
  {
    id: "conv155",
    category_id: "cat16",
    context: "JLPT N5 - expectation",
    content: "I'm looking forward to seeing you.",
    timestamp: "2023-10-02T11:10:00Z",
  },
  {
    id: "conv156",
    category_id: "cat16",
    context: "JLPT N5 - reason",
    content: "It's because I was sick.",
    timestamp: "2023-10-02T11:15:00Z",
  },
  {
    id: "conv157",
    category_id: "cat16",
    context: "JLPT N5 - sequence",
    content: "I studied after dinner.",
    timestamp: "2023-10-02T11:20:00Z",
  },
  {
    id: "conv158",
    category_id: "cat16",
    context: "JLPT N5 - hobby",
    content: "My hobby is taking pictures.",
    timestamp: "2023-10-02T11:25:00Z",
  },
  {
    id: "conv159",
    category_id: "cat16",
    context: "JLPT N5 - purpose",
    content: "I'm going to the library to study.",
    timestamp: "2023-10-02T11:30:00Z",
  },
  {
    id: "conv160",
    category_id: "cat16",
    context: "JLPT N5 - giving",
    content: "Please give me some water.",
    timestamp: "2023-10-02T11:35:00Z",
  },
  {
    id: "conv161",
    category_id: "cat16",
    context: "JLPT N5 - how",
    content: "How do you go to school?",
    timestamp: "2023-10-02T11:40:00Z",
  },
  {
    id: "conv162",
    category_id: "cat16",
    context: "JLPT N5 - quantity",
    content: "There are many books in this library.",
    timestamp: "2023-10-02T11:45:00Z",
  },
  {
    id: "conv163",
    category_id: "cat16",
    context: "JLPT N5 - comparison",
    content: "This apple is cheaper than that one.",
    timestamp: "2023-10-02T11:50:00Z",
  },
  {
    id: "conv164",
    category_id: "cat16",
    context: "JLPT N5 - ability",
    content: "I can't speak Japanese well.",
    timestamp: "2023-10-02T11:55:00Z",
  },
  {
    id: "conv165",
    category_id: "cat16",
    context: "JLPT N5 - request",
    content: "Please teach me Japanese.",
    timestamp: "2023-10-02T12:00:00Z",
  },
  {
    id: "conv166",
    category_id: "cat16",
    context: "JLPT N5 - routine",
    content: "I usually get up at six.",
    timestamp: "2023-10-02T12:05:00Z",
  },
  {
    id: "conv167",
    category_id: "cat16",
    context: "JLPT N5 - invitation",
    content: "Let's eat lunch together.",
    timestamp: "2023-10-02T12:10:00Z",
  },
  {
    id: "conv168",
    category_id: "cat16",
    context: "JLPT N5 - invitation",
    content: "Would you like to watch a movie with me?",
    timestamp: "2023-10-02T12:15:00Z",
  },
  {
    id: "conv169",
    category_id: "cat16",
    context: "JLPT N5 - desire",
    content: "I want to drink tea.",
    timestamp: "2023-10-02T12:20:00Z",
  },
  {
    id: "conv170",
    category_id: "cat16",
    context: "JLPT N5 - past tense",
    content: "Yesterday I went to the park.",
    timestamp: "2023-10-02T12:25:00Z",
  },
  {
    id: "conv171",
    category_id: "cat16",
    context: "JLPT N5 - request",
    content: "Please write your name here.",
    timestamp: "2023-10-02T12:30:00Z",
  },
  {
    id: "conv172",
    category_id: "cat16",
    context: "JLPT N5 - destination",
    content: "That train goes to Kyoto.",
    timestamp: "2023-10-02T12:35:00Z",
  },
  {
    id: "conv173",
    category_id: "cat16",
    context: "JLPT N5 - counters",
    content: "How many people are in your family?",
    timestamp: "2023-10-02T12:40:00Z",
  },

  // =========================================================
  // JLPT N4
  // =========================================================
  {
    id: "conv174",
    category_id: "cat17",
    context: "JLPT N4 - te shimau",
    content: "I've finished eating.",
    timestamp: "2023-10-02T13:00:00Z",
  },
  {
    id: "conv175",
    category_id: "cat17",
    context: "JLPT N4 - maybe",
    content: "I might be late.",
    timestamp: "2023-10-02T13:05:00Z",
  },
  {
    id: "conv176",
    category_id: "cat17",
    context: "JLPT N4 - obligation",
    content: "I have to go to work.",
    timestamp: "2023-10-02T13:10:00Z",
  },
  {
    id: "conv177",
    category_id: "cat17",
    context: "JLPT N4 - decision",
    content: "I've decided to study Japanese.",
    timestamp: "2023-10-02T13:15:00Z",
  },
  {
    id: "conv178",
    category_id: "cat17",
    context: "JLPT N4 - appearance",
    content: "That looks delicious.",
    timestamp: "2023-10-02T13:20:00Z",
  },
  {
    id: "conv179",
    category_id: "cat17",
    context: "JLPT N4 - nagara",
    content: "I read a book while drinking coffee.",
    timestamp: "2023-10-02T13:25:00Z",
  },
  {
    id: "conv180",
    category_id: "cat17",
    context: "JLPT N4 - overdo",
    content: "I ate too much.",
    timestamp: "2023-10-02T13:30:00Z",
  },
  {
    id: "conv181",
    category_id: "cat17",
    context: "JLPT N4 - conditional",
    content: "If it rains, I won't go.",
    timestamp: "2023-10-02T13:35:00Z",
  },
  {
    id: "conv182",
    category_id: "cat17",
    context: "JLPT N4 - conditional",
    content: "If I were you, I would go.",
    timestamp: "2023-10-02T13:40:00Z",
  },
  {
    id: "conv183",
    category_id: "cat17",
    context: "JLPT N4 - regret",
    content: "I wish I had studied more.",
    timestamp: "2023-10-02T13:45:00Z",
  },
  {
    id: "conv184",
    category_id: "cat17",
    context: "JLPT N4 - reason",
    content: "I couldn't go because I was busy.",
    timestamp: "2023-10-02T13:50:00Z",
  },
  {
    id: "conv185",
    category_id: "cat17",
    context: "JLPT N4 - appearance",
    content: "It looks like it's going to rain.",
    timestamp: "2023-10-02T13:55:00Z",
  },
  {
    id: "conv186",
    category_id: "cat17",
    context: "JLPT N4 - potential",
    content: "I can't eat wasabi.",
    timestamp: "2023-10-02T14:00:00Z",
  },
  {
    id: "conv187",
    category_id: "cat17",
    context: "JLPT N4 - passive",
    content: "I was told to work hard.",
    timestamp: "2023-10-02T14:05:00Z",
  },
  {
    id: "conv188",
    category_id: "cat17",
    context: "JLPT N4 - causative",
    content: "Please let me think for a moment.",
    timestamp: "2023-10-02T14:10:00Z",
  },
  {
    id: "conv189",
    category_id: "cat17",
    context: "JLPT N4 - tokoro",
    content: "I'm just about to leave.",
    timestamp: "2023-10-02T14:15:00Z",
  },
  {
    id: "conv190",
    category_id: "cat17",
    context: "JLPT N4 - bakari",
    content: "I just finished work.",
    timestamp: "2023-10-02T14:20:00Z",
  },
  {
    id: "conv191",
    category_id: "cat17",
    context: "JLPT N4 - experience",
    content: "I have been to Japan.",
    timestamp: "2023-10-02T14:25:00Z",
  },
  {
    id: "conv192",
    category_id: "cat17",
    context: "JLPT N4 - sequence",
    content: "I go to the gym after work.",
    timestamp: "2023-10-02T14:30:00Z",
  },
  {
    id: "conv193",
    category_id: "cat17",
    context: "JLPT N4 - not yet",
    content: "I haven't seen that movie yet.",
    timestamp: "2023-10-02T14:35:00Z",
  },
  {
    id: "conv194",
    category_id: "cat17",
    context: "JLPT N4 - while",
    content: "I listened to music while studying.",
    timestamp: "2023-10-02T14:40:00Z",
  },
  {
    id: "conv195",
    category_id: "cat17",
    context: "JLPT N4 - giving",
    content: "I gave my friend a present.",
    timestamp: "2023-10-02T14:45:00Z",
  },
  {
    id: "conv196",
    category_id: "cat17",
    context: "JLPT N4 - giving",
    content: "My friend gave me a present.",
    timestamp: "2023-10-02T14:50:00Z",
  },
  {
    id: "conv197",
    category_id: "cat17",
    context: "JLPT N4 - receiving",
    content: "I received a present from my friend.",
    timestamp: "2023-10-02T14:55:00Z",
  },
  {
    id: "conv198",
    category_id: "cat17",
    context: "JLPT N4 - skill",
    content: "I'm good at cooking.",
    timestamp: "2023-10-02T15:00:00Z",
  },
  {
    id: "conv199",
    category_id: "cat17",
    context: "JLPT N4 - skill",
    content: "I'm bad at singing.",
    timestamp: "2023-10-02T15:05:00Z",
  },
  {
    id: "conv200",
    category_id: "cat17",
    context: "JLPT N4 - become",
    content: "It has become cold.",
    timestamp: "2023-10-02T15:10:00Z",
  },
  {
    id: "conv201",
    category_id: "cat17",
    context: "JLPT N4 - desire",
    content: "I want a new phone.",
    timestamp: "2023-10-02T15:15:00Z",
  },
  {
    id: "conv202",
    category_id: "cat17",
    context: "JLPT N4 - whether",
    content: "I don't know whether it's true.",
    timestamp: "2023-10-02T15:20:00Z",
  },
  {
    id: "conv203",
    category_id: "cat17",
    context: "JLPT N4 - approximate",
    content: "It's about ten minutes from here.",
    timestamp: "2023-10-02T15:25:00Z",
  },
  {
    id: "conv204",
    category_id: "cat17",
    context: "JLPT N4 - habit",
    content: "I try to get up early.",
    timestamp: "2023-10-02T15:30:00Z",
  },
  {
    id: "conv205",
    category_id: "cat17",
    context: "JLPT N4 - try",
    content: "Please try eating this.",
    timestamp: "2023-10-02T15:35:00Z",
  },
  {
    id: "conv206",
    category_id: "cat17",
    context: "JLPT N4 - easy to",
    content: "This machine is easy to use.",
    timestamp: "2023-10-02T15:40:00Z",
  },
  {
    id: "conv207",
    category_id: "cat17",
    context: "JLPT N4 - hard to",
    content: "This book is hard to read.",
    timestamp: "2023-10-02T15:45:00Z",
  },
  {
    id: "conv208",
    category_id: "cat17",
    context: "JLPT N4 - sequence",
    content: "I went to Kyoto and saw temples.",
    timestamp: "2023-10-02T15:50:00Z",
  },
  {
    id: "conv209",
    category_id: "cat17",
    context: "JLPT N4 - before",
    content: "Please tell me before you leave.",
    timestamp: "2023-10-02T15:55:00Z",
  },
  {
    id: "conv210",
    category_id: "cat17",
    context: "JLPT N4 - after",
    content: "After eating, let's go for a walk.",
    timestamp: "2023-10-02T16:00:00Z",
  },
  {
    id: "conv211",
    category_id: "cat17",
    context: "JLPT N4 - obligation",
    content: "I need to buy a ticket.",
    timestamp: "2023-10-02T16:05:00Z",
  },
  {
    id: "conv212",
    category_id: "cat17",
    context: "JLPT N4 - suggestion",
    content: "Why don't we take a rest?",
    timestamp: "2023-10-02T16:10:00Z",
  },
  {
    id: "conv213",
    category_id: "cat17",
    context: "JLPT N4 - resolve",
    content: "Even if it's hard, I'll keep going.",
    timestamp: "2023-10-02T16:15:00Z",
  },

  // =========================================================
  // JLPT N3
  // =========================================================
  {
    id: "conv214",
    category_id: "cat18",
    context: "JLPT N3 - beki",
    content: "I should study more.",
    timestamp: "2023-10-02T17:00:00Z",
  },
  {
    id: "conv215",
    category_id: "cat18",
    context: "JLPT N3 - rashii",
    content: "He seems to be a teacher.",
    timestamp: "2023-10-02T17:05:00Z",
  },
  {
    id: "conv216",
    category_id: "cat18",
    context: "JLPT N3 - ppoi",
    content: "This apple tastes a bit sweet.",
    timestamp: "2023-10-02T17:10:00Z",
  },
  {
    id: "conv217",
    category_id: "cat18",
    context: "JLPT N3 - kagiri",
    content: "As long as I'm alive, I won't forget you.",
    timestamp: "2023-10-02T17:15:00Z",
  },
  {
    id: "conv218",
    category_id: "cat18",
    context: "JLPT N3 - uchi ni",
    content: "While I was reading, it got dark.",
    timestamp: "2023-10-02T17:20:00Z",
  },
  {
    id: "conv219",
    category_id: "cat18",
    context: "JLPT N3 - passive",
    content: "I was scolded by my boss.",
    timestamp: "2023-10-02T17:25:00Z",
  },
  {
    id: "conv220",
    category_id: "cat18",
    context: "JLPT N3 - causative",
    content: "I made my son do his homework.",
    timestamp: "2023-10-02T17:30:00Z",
  },
  {
    id: "conv221",
    category_id: "cat18",
    context: "JLPT N3 - wake ni wa ikanai",
    content: "I can't just sit here and wait.",
    timestamp: "2023-10-02T17:35:00Z",
  },
  {
    id: "conv222",
    category_id: "cat18",
    context: "JLPT N3 - zaru o enai",
    content: "I have no choice but to apologize.",
    timestamp: "2023-10-02T17:40:00Z",
  },
  {
    id: "conv223",
    category_id: "cat18",
    context: "JLPT N3 - tsumori",
    content: "I plan to go to Osaka next month.",
    timestamp: "2023-10-02T17:45:00Z",
  },
  {
    id: "conv224",
    category_id: "cat18",
    context: "JLPT N3 - okage de",
    content: "Thanks to you, I passed the exam.",
    timestamp: "2023-10-02T17:50:00Z",
  },
  {
    id: "conv225",
    category_id: "cat18",
    context: "JLPT N3 - sei de",
    content: "Because of the rain, the game was canceled.",
    timestamp: "2023-10-02T17:55:00Z",
  },
  {
    id: "conv226",
    category_id: "cat18",
    context: "JLPT N3 - to (when)",
    content: "As soon as I got home, I made tea.",
    timestamp: "2023-10-02T18:00:00Z",
  },
  {
    id: "conv227",
    category_id: "cat18",
    context: "JLPT N3 - te mo",
    content: "No matter who comes, it's the same.",
    timestamp: "2023-10-02T18:05:00Z",
  },
  {
    id: "conv228",
    category_id: "cat18",
    context: "JLPT N3 - node",
    content: "It's cold, so I'll turn on the heater.",
    timestamp: "2023-10-02T18:10:00Z",
  },
  {
    id: "conv229",
    category_id: "cat18",
    context: "JLPT N3 - experience",
    content: "I have been to Kyoto many times.",
    timestamp: "2023-10-02T18:15:00Z",
  },
  {
    id: "conv230",
    category_id: "cat18",
    context: "JLPT N3 - te morau",
    content: "My teacher taught me how to write kanji.",
    timestamp: "2023-10-02T18:20:00Z",
  },
  {
    id: "conv231",
    category_id: "cat18",
    context: "JLPT N3 - you ni suru",
    content: "I make a point of reading before bed.",
    timestamp: "2023-10-02T18:25:00Z",
  },
  {
    id: "conv232",
    category_id: "cat18",
    context: "JLPT N3 - hearsay",
    content: "I hear the new store is popular.",
    timestamp: "2023-10-02T18:30:00Z",
  },
  {
    id: "conv233",
    category_id: "cat18",
    context: "JLPT N3 - mitai",
    content: "It looks like a good restaurant.",
    timestamp: "2023-10-02T18:35:00Z",
  },
  {
    id: "conv234",
    category_id: "cat18",
    context: "JLPT N3 - regret",
    content: "I wish you had told me earlier.",
    timestamp: "2023-10-02T18:40:00Z",
  },
  {
    id: "conv235",
    category_id: "cat18",
    context: "JLPT N3 - prohibition",
    content: "You must not tell anyone.",
    timestamp: "2023-10-02T18:45:00Z",
  },
  {
    id: "conv236",
    category_id: "cat18",
    context: "JLPT N3 - ni kakawarazu",
    content: "It doesn't matter how old you are.",
    timestamp: "2023-10-02T18:50:00Z",
  },
  {
    id: "conv237",
    category_id: "cat18",
    context: "JLPT N3 - endurance",
    content: "I can't stand the heat.",
    timestamp: "2023-10-02T18:55:00Z",
  },
  {
    id: "conv238",
    category_id: "cat18",
    context: "JLPT N3 - bakari",
    content: "He keeps complaining.",
    timestamp: "2023-10-02T19:00:00Z",
  },
  {
    id: "conv239",
    category_id: "cat18",
    context: "JLPT N3 - clause",
    content: "I saw a big dog running.",
    timestamp: "2023-10-02T19:05:00Z",
  },
  {
    id: "conv240",
    category_id: "cat18",
    context: "JLPT N3 - without",
    content: "I leave home without eating breakfast.",
    timestamp: "2023-10-02T19:10:00Z",
  },
  {
    id: "conv241",
    category_id: "cat18",
    context: "JLPT N3 - gradual change",
    content: "It's getting hotter and hotter.",
    timestamp: "2023-10-02T19:15:00Z",
  },
  {
    id: "conv242",
    category_id: "cat18",
    context: "JLPT N3 - tara",
    content: "I'll let you know when I get there.",
    timestamp: "2023-10-02T19:20:00Z",
  },
  {
    id: "conv243",
    category_id: "cat18",
    context: "JLPT N3 - tara",
    content: "If it were sunny, we could go out.",
    timestamp: "2023-10-02T19:25:00Z",
  },
  {
    id: "conv244",
    category_id: "cat18",
    context: "JLPT N3 - expectation",
    content: "I thought it would snow, but it didn't.",
    timestamp: "2023-10-02T19:30:00Z",
  },
  {
    id: "conv245",
    category_id: "cat18",
    context: "JLPT N3 - request",
    content: "Please send me an email before you leave.",
    timestamp: "2023-10-02T19:35:00Z",
  },
  {
    id: "conv246",
    category_id: "cat18",
    context: "JLPT N3 - touzen",
    content: "It's natural that he's tired.",
    timestamp: "2023-10-02T19:40:00Z",
  },
  {
    id: "conv247",
    category_id: "cat18",
    context: "JLPT N3 - almost",
    content: "I almost missed the train.",
    timestamp: "2023-10-02T19:45:00Z",
  },
  {
    id: "conv248",
    category_id: "cat18",
    context: "JLPT N3 - almost",
    content: "I almost got into an accident.",
    timestamp: "2023-10-02T19:50:00Z",
  },
  {
    id: "conv249",
    category_id: "cat18",
    context: "JLPT N3 - aatarimae",
    content: "Overtime is normal in this company.",
    timestamp: "2023-10-02T19:55:00Z",
  },
  {
    id: "conv250",
    category_id: "cat18",
    context: "JLPT N3 - request",
    content: "I'll do my best, so please support me.",
    timestamp: "2023-10-02T20:00:00Z",
  },
  {
    id: "conv251",
    category_id: "cat18",
    context: "JLPT N3 - keigo",
    content: "Would you mind opening the window?",
    timestamp: "2023-10-02T20:05:00Z",
  },
  {
    id: "conv252",
    category_id: "cat18",
    context: "JLPT N3 - keigo",
    content: "Is this okay?",
    timestamp: "2023-10-02T20:10:00Z",
  },
  {
    id: "conv253",
    category_id: "cat18",
    context: "JLPT N3 - keigo",
    content: "I'm honored to meet you.",
    timestamp: "2023-10-02T20:15:00Z",
  },

  // =========================================================
  // Casual Slang
  // =========================================================
  {
    id: "conv254",
    category_id: "cat19",
    context: "Slang - reaction",
    content: "Yabai! (amazing / terrible / oh no)",
    timestamp: "2023-10-02T21:00:00Z",
  },
  {
    id: "conv255",
    category_id: "cat19",
    context: "Slang - reaction",
    content: "Maji de? (Seriously? / For real?)",
    timestamp: "2023-10-02T21:05:00Z",
  },
  {
    id: "conv256",
    category_id: "cat19",
    context: "Slang - reaction",
    content: "Ukeru (That's hilarious!)",
    timestamp: "2023-10-02T21:10:00Z",
  },
  {
    id: "conv257",
    category_id: "cat19",
    context: "Slang - agreement",
    content: "Sore na! (Exactly! / I know, right?)",
    timestamp: "2023-10-02T21:15:00Z",
  },
  {
    id: "conv258",
    category_id: "cat19",
    context: "Slang - complaint",
    content: "Uzai (annoying / a pain)",
    timestamp: "2023-10-02T21:20:00Z",
  },
  {
    id: "conv259",
    category_id: "cat19",
    context: "Slang - complaint",
    content: "Kimoi (gross / creepy)",
    timestamp: "2023-10-02T21:25:00Z",
  },
  {
    id: "conv260",
    category_id: "cat19",
    context: "Slang - complaint",
    content: "Mukatsuku (pissed off / irritated)",
    timestamp: "2023-10-02T21:30:00Z",
  },
  {
    id: "conv261",
    category_id: "cat19",
    context: "Slang - emphasis",
    content: "Gachi (serious / for real)",
    timestamp: "2023-10-02T21:35:00Z",
  },
  {
    id: "conv262",
    category_id: "cat19",
    context: "Slang - praise",
    content: "Hanpa nai (insane / awesome)",
    timestamp: "2023-10-02T21:40:00Z",
  },
  {
    id: "conv263",
    category_id: "cat19",
    context: "Slang - reaction",
    content: "Bimyou (meh / iffy / so-so)",
    timestamp: "2023-10-02T21:45:00Z",
  },
  {
    id: "conv264",
    category_id: "cat19",
    context: "Slang - insult",
    content: "Dasai (uncool / out of style)",
    timestamp: "2023-10-02T21:50:00Z",
  },
  {
    id: "conv265",
    category_id: "cat19",
    context: "Slang - praise",
    content: "Egui (awesome / incredible)",
    timestamp: "2023-10-02T21:55:00Z",
  },
  {
    id: "conv266",
    category_id: "cat19",
    context: "Slang - greeting",
    content: "Ossu! (Yo! / What's up, dude?)",
    timestamp: "2023-10-02T22:00:00Z",
  },
  {
    id: "conv267",
    category_id: "cat19",
    context: "Slang - reply",
    content: "Wakannai (I don't know)",
    timestamp: "2023-10-02T22:05:00Z",
  },
  {
    id: "conv268",
    category_id: "cat19",
    context: "Slang - online",
    content: "Warota (lol / I laughed)",
    timestamp: "2023-10-02T22:10:00Z",
  },
  {
    id: "conv269",
    category_id: "cat19",
    context: "Slang - online",
    content: "Kusa / www (lol / hahaha)",
    timestamp: "2023-10-02T22:15:00Z",
  },
  {
    id: "conv270",
    category_id: "cat19",
    context: "Slang - feeling",
    content: "Emoi (nostalgic / deeply moving)",
    timestamp: "2023-10-02T22:20:00Z",
  },
  {
    id: "conv271",
    category_id: "cat19",
    context: "Slang - praise",
    content: "Kawachii (so cute)",
    timestamp: "2023-10-02T22:25:00Z",
  },
  {
    id: "conv272",
    category_id: "cat19",
    context: "Slang - emphasis",
    content: "Meccha (super / very)",
    timestamp: "2023-10-02T22:30:00Z",
  },
  {
    id: "conv273",
    category_id: "cat19",
    context: "Slang - Kansai",
    content: "Aho (idiot)",
    timestamp: "2023-10-02T22:35:00Z",
  },
  {
    id: "conv274",
    category_id: "cat19",
    context: "Slang - Kansai",
    content: "Ookini (thanks)",
    timestamp: "2023-10-02T22:40:00Z",
  },
  {
    id: "conv275",
    category_id: "cat19",
    context: "Slang - Kansai",
    content: "Honma (really? / for real?)",
    timestamp: "2023-10-02T22:45:00Z",
  },
  {
    id: "conv276",
    category_id: "cat19",
    context: "Slang - Kansai",
    content: "Akan (bad / no good)",
    timestamp: "2023-10-02T22:50:00Z",
  },
  {
    id: "conv277",
    category_id: "cat19",
    context: "Slang - Kansai",
    content: "Omoroi (funny / interesting)",
    timestamp: "2023-10-02T22:55:00Z",
  },
  {
    id: "conv278",
    category_id: "cat19",
    context: "Slang - Kansai",
    content: "Chau de! (That's not it! / Wrong!)",
    timestamp: "2023-10-02T23:00:00Z",
  },
  {
    id: "conv279",
    category_id: "cat19",
    context: "Slang - tech",
    content: "Sumaho (smartphone)",
    timestamp: "2023-10-02T23:05:00Z",
  },
  {
    id: "conv280",
    category_id: "cat19",
    context: "Slang - tech",
    content: "Guguru (to Google something)",
    timestamp: "2023-10-02T23:10:00Z",
  },
  {
    id: "conv281",
    category_id: "cat19",
    context: "Slang - tech",
    content: "Disuru (to diss / badmouth)",
    timestamp: "2023-10-02T23:15:00Z",
  },
  {
    id: "conv282",
    category_id: "cat19",
    context: "Slang - action",
    content: "Saboru (to skip / slack off)",
    timestamp: "2023-10-02T23:20:00Z",
  },
  {
    id: "conv283",
    category_id: "cat19",
    context: "Slang - action",
    content: "Moteru (to be popular with the opposite sex)",
    timestamp: "2023-10-02T23:25:00Z",
  },
  {
    id: "conv284",
    category_id: "cat19",
    context: "Slang - phrase",
    content: "Donmai (don't worry about it)",
    timestamp: "2023-10-02T23:30:00Z",
  },
  {
    id: "conv285",
    category_id: "cat19",
    context: "Slang - action",
    content: "Chiruru (to chill / relax)",
    timestamp: "2023-10-02T23:35:00Z",
  },
  {
    id: "conv286",
    category_id: "cat19",
    context: "Slang - action",
    content: "Hamaru (to be hooked / obsessed)",
    timestamp: "2023-10-02T23:40:00Z",
  },
  {
    id: "conv287",
    category_id: "cat19",
    context: "Slang - reaction",
    content: "Uso! (No way! / You're lying!)",
    timestamp: "2023-10-02T23:45:00Z",
  },
  {
    id: "conv288",
    category_id: "cat19",
    context: "Slang - greeting",
    content: "Choushi dou? (How's it going?)",
    timestamp: "2023-10-02T23:50:00Z",
  },
  {
    id: "conv289",
    category_id: "cat19",
    context: "Slang - apology",
    content: "Warii ne (my bad)",
    timestamp: "2023-10-02T23:55:00Z",
  },
  {
    id: "conv290",
    category_id: "cat19",
    context: "Slang - greeting",
    content: "Otsu (good work / see ya)",
    timestamp: "2023-10-03T00:00:00Z",
  },
  {
    id: "conv291",
    category_id: "cat19",
    context: "Slang - praise",
    content: "Nori ga ii (easygoing / goes with the flow)",
    timestamp: "2023-10-03T00:05:00Z",
  },
  {
    id: "conv292",
    category_id: "cat19",
    context: "Slang - insult",
    content: "Zakko (cheap / low quality)",
    timestamp: "2023-10-03T00:10:00Z",
  },
  {
    id: "conv293",
    category_id: "cat19",
    context: "Slang - action",
    content: "Nampa (to hit on / pick someone up)",
    timestamp: "2023-10-03T00:15:00Z",
  },
  {
    id: "conv294",
    category_id: "cat19",
    context: "Slang - people",
    content: "Paripi (party people)",
    timestamp: "2023-10-03T00:20:00Z",
  },
  {
    id: "conv295",
    category_id: "cat19",
    context: "Slang - people",
    content: "Otaku (obsessed fan of anime/manga)",
    timestamp: "2023-10-03T00:25:00Z",
  },
  {
    id: "conv296",
    category_id: "cat19",
    context: "Slang - emphasis",
    content: "Cho (super / totally)",
    timestamp: "2023-10-03T00:30:00Z",
  },
  {
    id: "conv297",
    category_id: "cat19",
    context: "Slang - reaction",
    content: "Sugoi! (Amazing! / Wow!)",
    timestamp: "2023-10-03T00:35:00Z",
  },
  {
    id: "conv298",
    category_id: "cat19",
    context: "Slang - invitation",
    content: "Ippai dou? (Want to grab a drink?)",
    timestamp: "2023-10-03T00:40:00Z",
  },
  {
    id: "conv299",
    category_id: "cat19",
    context: "Slang - phrase",
    content: "Toriaezu biiru (a beer for now)",
    timestamp: "2023-10-03T00:45:00Z",
  },
  {
    id: "conv300",
    category_id: "cat19",
    context: "Slang - online",
    content: "Daretoku (who benefits? / Y tho)",
    timestamp: "2023-10-03T00:50:00Z",
  },
  {
    id: "conv301",
    category_id: "cat19",
    context: "Slang - online",
    content: "KY (can't read the room)",
    timestamp: "2023-10-03T00:55:00Z",
  },
  {
    id: "conv302",
    category_id: "cat19",
    context: "Slang - online",
    content: "Nau (right now)",
    timestamp: "2023-10-03T01:00:00Z",
  },
  {
    id: "conv303",
    category_id: "cat19",
    context: "Slang - phrase",
    content: "Tehepero (oops, my bad - cutesy)",
    timestamp: "2023-10-03T01:05:00Z",
  },

  // =========================================================
  // Rakuten guide additions
  // =========================================================
  {
    id: "conv304",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Do you have an English menu?",
    timestamp: "2023-10-03T02:00:00Z",
  },
  {
    id: "conv305",
    category_id: "cat2",
    context: "At a restaurant",
    content: "Do you have any recommendations?",
    timestamp: "2023-10-03T02:05:00Z",
  },
  {
    id: "conv306",
    category_id: "cat4",
    context: "At a train station",
    content: "I'm getting off here.",
    timestamp: "2023-10-03T02:10:00Z",
  },
  {
    id: "conv307",
    category_id: "cat9",
    context: "In an emergency",
    content: "Please call an ambulance.",
    timestamp: "2023-10-03T02:15:00Z",
  },
  {
    id: "conv308",
    category_id: "cat9",
    context: "Not feeling well",
    content: "I have a fever.",
    timestamp: "2023-10-03T02:20:00Z",
  },
  {
    id: "conv309",
    category_id: "cat9",
    context: "Not feeling well",
    content: "I have a cough.",
    timestamp: "2023-10-03T02:25:00Z",
  },
  {
    id: "conv310",
    category_id: "cat9",
    context: "In pain",
    content: "It hurts.",
    timestamp: "2023-10-03T02:30:00Z",
  },
]

export const translations: Translation[] = [
  // Convenience Store
  {
    conversation_id: "conv1",
    translation: "すみません、お菓子はどこにありますか？",
    pronunciation: "Sumimasen, okashi wa doko ni arimasu ka?",
  },
  {
    conversation_id: "conv2",
    translation: "この飲み物はいくらですか？",
    pronunciation: "Kono nomimono wa ikura desu ka?",
  },
  {
    conversation_id: "conv7",
    translation: "トイレはどこですか？",
    pronunciation: "Toire wa doko desu ka?",
  },
  {
    conversation_id: "conv9",
    translation: "クレジットカードで払えますか？",
    pronunciation: "Kurejitto kaado de haraemasu ka?",
  },
  {
    conversation_id: "conv10",
    translation: "袋をもらえますか？",
    pronunciation: "Fukuro o moraemasu ka?",
  },
  {
    conversation_id: "conv11",
    translation: "これを温めてもらえますか？",
    pronunciation: "Kore o atatamete moraemasu ka?",
  },
  {
    conversation_id: "conv12",
    translation: "ここでSIMカードを買えますか？",
    pronunciation: "Koko de SIM kaado o kaemasu ka?",
  },
  {
    conversation_id: "conv13",
    translation: "ATMは使えますか？",
    pronunciation: "ATM wa tsukaemasu ka?",
  },
  {
    conversation_id: "conv14",
    translation: "キャッシュレス決済は使えますか？",
    pronunciation: "Kyasshuresu kessai wa tsukaemasu ka?",
  },

  // Restaurant
  {
    conversation_id: "conv3",
    translation: "メニューを見せていただけますか？",
    pronunciation: "Menyuu o misete itadakemasu ka?",
  },
  {
    conversation_id: "conv4",
    translation: "寿司を注文したいです。",
    pronunciation: "Sushi o chuumon shitai desu.",
  },
  {
    conversation_id: "conv8",
    translation: "お会計をお願いします。",
    pronunciation: "Okaikei o onegaishimasu.",
  },
  {
    conversation_id: "conv15",
    translation: "二人ですが、席はありますか？",
    pronunciation: "Futari desu ga, seki wa arimasu ka?",
  },
  {
    conversation_id: "conv16",
    translation: "予約は必要ですか？",
    pronunciation: "Yoyaku wa hitsuyou desu ka?",
  },
  {
    conversation_id: "conv17",
    translation: "おすすめは何ですか？",
    pronunciation: "Osusume wa nan desu ka?",
  },
  {
    conversation_id: "conv18",
    translation: "この料理は辛いですか？",
    pronunciation: "Kono ryouri wa karai desu ka?",
  },
  {
    conversation_id: "conv19",
    translation: "豚肉を食べません。",
    pronunciation: "Buta-niku wo tabemasen",
  },
  {
    conversation_id: "conv20",
    translation: "お水をいただけますか？",
    pronunciation: "Omizu o itadakemasu ka?",
  },
  {
    conversation_id: "conv21",
    translation: "別々に払えますか？",
    pronunciation: "Betsubetsu ni haraemasu ka?",
  },
  {
    conversation_id: "conv22",
    translation: "サービス料は含まれていますか？",
    pronunciation: "Saabisu-ryou wa fukumarete imasu ka?",
  },

  // Shopping
  {
    conversation_id: "conv5",
    translation: "これの大きいサイズはありますか？",
    pronunciation: "Kore no ookii saizu wa arimasu ka?",
  },
  {
    conversation_id: "conv6",
    translation: "これを試着してもいいですか？",
    pronunciation: "Kore o shichaku shite mo ii desu ka?",
  },
  {
    conversation_id: "conv23",
    translation: "別の色はありますか？",
    pronunciation: "Betsu no iro wa arimasu ka?",
  },
  {
    conversation_id: "conv24",
    translation: "これはいくらですか？",
    pronunciation: "Kore wa ikura desu ka?",
  },
  {
    conversation_id: "conv25",
    translation: "これはセールですか？",
    pronunciation: "Kore wa seeru desu ka?",
  },
  {
    conversation_id: "conv26",
    translation: "もっと小さいサイズはありますか？",
    pronunciation: "Motto chiisai saizu wa arimasu ka?",
  },
  {
    conversation_id: "conv27",
    translation: "クレジットカードで払えますか？",
    pronunciation: "Kurejitto kaado de haraemasu ka?",
  },
  {
    conversation_id: "conv28",
    translation: "免税できますか？",
    pronunciation: "Menzei dekimasu ka?",
  },
  {
    conversation_id: "conv29",
    translation: "試着室はどこですか？",
    pronunciation: "Shichakushitsu wa doko desu ka?",
  },
  {
    conversation_id: "conv30",
    translation: "返品できますか？",
    pronunciation: "Henpin dekimasu ka?",
  },

  // Transportation
  {
    conversation_id: "conv31",
    translation: "切符売り場はどこですか？",
    pronunciation: "Kippu uriba wa doko desu ka?",
  },
  {
    conversation_id: "conv32",
    translation: "東京行きの電車はどれですか？",
    pronunciation: "Toukyou-yuki no densha wa dore desu ka?",
  },
  {
    conversation_id: "conv33",
    translation: "何番線に行けばいいですか？",
    pronunciation: "Nan-bansen ni ikeba ii desu ka?",
  },
  {
    conversation_id: "conv34",
    translation: "京都までの切符はいくらですか？",
    pronunciation: "Kyouto made no kippu wa ikura desu ka?",
  },
  {
    conversation_id: "conv35",
    translation: "この電車は大阪行きですか？",
    pronunciation: "Kono densha wa Oosaka-yuki desu ka?",
  },
  {
    conversation_id: "conv36",
    translation: "ICカードはどこでチャージできますか？",
    pronunciation: "IC kaado wa doko de chaaji dekimasu ka?",
  },
  {
    conversation_id: "conv37",
    translation: "次の電車はいつですか？",
    pronunciation: "Tsugi no densha wa itsu desu ka?",
  },
  {
    conversation_id: "conv38",
    translation: "この住所までお願いします。",
    pronunciation: "Kono juusho made onegaishimasu.",
  },
  {
    conversation_id: "conv39",
    translation: "いくらくらいかかりますか？",
    pronunciation: "Ikura kurai kakarimasu ka?",
  },
  {
    conversation_id: "conv40",
    translation: "このバスは駅に行きますか？",
    pronunciation: "Kono basu wa eki ni ikimasu ka?",
  },

  // Hotel
  {
    conversation_id: "conv41",
    translation: "予約しています。",
    pronunciation: "Yoyaku shiteimasu.",
  },
  {
    conversation_id: "conv42",
    translation: "チェックインをお願いします。",
    pronunciation: "Chekkuin o onegaishimasu.",
  },
  {
    conversation_id: "conv43",
    translation: "チェックアウトは何時ですか？",
    pronunciation: "Chekkuauto wa nanji desu ka?",
  },
  {
    conversation_id: "conv44",
    translation: "朝食は含まれていますか？",
    pronunciation: "Choushoku wa fukumarete imasu ka?",
  },
  {
    conversation_id: "conv45",
    translation: "荷物を預かってもらえますか？",
    pronunciation: "Nimotsu o azukatte moraemasu ka?",
  },
  {
    conversation_id: "conv46",
    translation: "タクシーを呼んでもらえますか？",
    pronunciation: "Takushii o yonde moraemasu ka?",
  },
  {
    conversation_id: "conv47",
    translation: "部屋にWi-Fiはありますか？",
    pronunciation: "Heya ni Wi-Fi wa arimasu ka?",
  },
  {
    conversation_id: "conv48",
    translation: "タオルをもう一枚いただけますか？",
    pronunciation: "Taoru o mou ichimai itadakemasu ka?",
  },

  // Airport
  {
    conversation_id: "conv49",
    translation: "チェックインカウンターはどこですか？",
    pronunciation: "Chekkuin kauntaa wa doko desu ka?",
  },
  {
    conversation_id: "conv50",
    translation: "手荷物受取所はどこですか？",
    pronunciation: "Tenimotsu uketori-jo wa doko desu ka?",
  },
  {
    conversation_id: "conv51",
    translation: "搭乗口はどこですか？",
    pronunciation: "Toujouguchi wa doko desu ka?",
  },
  {
    conversation_id: "conv52",
    translation: "何個まで荷物を預けられますか？",
    pronunciation: "Nanko made nimotsu o azukeraremasu ka?",
  },
  {
    conversation_id: "conv53",
    translation: "両替所はどこですか？",
    pronunciation: "Ryougaejo wa doko desu ka?",
  },
  {
    conversation_id: "conv54",
    translation: "SIMカードはどこで買えますか？",
    pronunciation: "SIM kaado wa doko de kaemasu ka?",
  },

  // Sightseeing
  {
    conversation_id: "conv55",
    translation: "ここへはどうやって行けばいいですか？",
    pronunciation: "Koko e wa dou yatte ikeba ii desu ka?",
  },
  {
    conversation_id: "conv56",
    translation: "入場料はいくらですか？",
    pronunciation: "Nyuujouryou wa ikura desu ka?",
  },
  {
    conversation_id: "conv57",
    translation: "何時に開きますか？",
    pronunciation: "Nanji ni akimasu ka?",
  },
  {
    conversation_id: "conv58",
    translation: "ここで写真を撮ってもいいですか？",
    pronunciation: "Koko de shashin o totte mo ii desu ka?",
  },
  {
    conversation_id: "conv59",
    translation: "この近くに有名な場所はありますか？",
    pronunciation: "Kono chikaku ni yuumei na basho wa arimasu ka?",
  },
  {
    conversation_id: "conv60",
    translation: "写真を撮っていただけますか？",
    pronunciation: "Shashin o totte itadakemasu ka?",
  },

  // Everyday conversation
  {
    conversation_id: "conv61",
    translation: "はじめまして。",
    pronunciation: "Hajimemashite.",
  },
  {
    conversation_id: "conv62",
    translation: "どちらから来ましたか？",
    pronunciation: "Dochira kara kimashita ka?",
  },
  {
    conversation_id: "conv63",
    translation: "英語を話せますか？",
    pronunciation: "Eigo o hanasemasu ka?",
  },
  {
    conversation_id: "conv64",
    translation: "もう少しゆっくり話していただけますか？",
    pronunciation: "Mou sukoshi yukkuri hanashite itadakemasu ka?",
  },
  {
    conversation_id: "conv65",
    translation: "もう一度言っていただけますか？",
    pronunciation: "Mou ichido itte itadakemasu ka?",
  },
  {
    conversation_id: "conv66",
    translation: "分かりません。",
    pronunciation: "Wakarimasen.",
  },
  {
    conversation_id: "conv67",
    translation: "助けていただいてありがとうございます。",
    pronunciation: "Tasukete itadaite arigatou gozaimasu.",
  },
  {
    conversation_id: "conv68",
    translation: "すみません。",
    pronunciation: "Sumimasen.",
  },

  // Emergency
  {
    conversation_id: "conv69",
    translation: "助けてください。",
    pronunciation: "Tasukete kudasai.",
  },
  {
    conversation_id: "conv70",
    translation: "一番近い病院はどこですか？",
    pronunciation: "Ichiban chikai byouin wa doko desu ka?",
  },
  {
    conversation_id: "conv71",
    translation: "財布をなくしました。",
    pronunciation: "Saifu o nakushimashita.",
  },
  {
    conversation_id: "conv72",
    translation: "パスポートをなくしました。",
    pronunciation: "Pasupooto o nakushimashita.",
  },
  {
    conversation_id: "conv73",
    translation: "届け出をしたいです。",
    pronunciation: "Todokede o shitai desu.",
  },

  // Animal Vocabulary (Doubutsu)
  { conversation_id: "conv74", translation: "いぬ", pronunciation: "inu" },
  { conversation_id: "conv75", translation: "うま", pronunciation: "uma" },
  { conversation_id: "conv76", translation: "くま", pronunciation: "kuma" },
  { conversation_id: "conv77", translation: "ぞう", pronunciation: "zou" },
  { conversation_id: "conv78", translation: "さい", pronunciation: "sai" },
  { conversation_id: "conv79", translation: "ねこ", pronunciation: "neko" },
  { conversation_id: "conv80", translation: "うし", pronunciation: "ushi" },
  { conversation_id: "conv81", translation: "しか", pronunciation: "shika" },
  { conversation_id: "conv82", translation: "かば", pronunciation: "kaba" },
  { conversation_id: "conv83", translation: "やぎ", pronunciation: "yagi" },
  { conversation_id: "conv84", translation: "ぶた", pronunciation: "buta" },
  { conversation_id: "conv85", translation: "ろば", pronunciation: "roba" },
  { conversation_id: "conv86", translation: "とら", pronunciation: "tora" },
  { conversation_id: "conv87", translation: "りす", pronunciation: "risu" },
  { conversation_id: "conv88", translation: "かめ", pronunciation: "kame" },
  { conversation_id: "conv89", translation: "ひょう", pronunciation: "hyou" },
  { conversation_id: "conv90", translation: "さる", pronunciation: "saru" },
  { conversation_id: "conv91", translation: "いか", pronunciation: "ika" },
  { conversation_id: "conv92", translation: "さめ", pronunciation: "same" },
  { conversation_id: "conv93", translation: "へび", pronunciation: "hebi" },
  { conversation_id: "conv94", translation: "わに", pronunciation: "wani" },
  { conversation_id: "conv95", translation: "たこ", pronunciation: "tako" },
  { conversation_id: "conv96", translation: "かに", pronunciation: "kani" },
  { conversation_id: "conv97", translation: "あり", pronunciation: "ari" },
  { conversation_id: "conv98", translation: "つる", pronunciation: "tsuru" },

  // Self-introduction
  {
    conversation_id: "conv99",
    translation: "私の名前はアンディです。",
    pronunciation: "Watashi no namae wa Andi desu.",
  },
  {
    conversation_id: "conv100",
    translation: "私はインドネシア人です。",
    pronunciation: "Watashi wa Indoneshia-jin desu.",
  },
  {
    conversation_id: "conv101",
    translation: "ジャカルタから来ました。",
    pronunciation: "Jakaruta kara kimashita.",
  },
  {
    conversation_id: "conv102",
    translation: "どうぞよろしくお願いします。",
    pronunciation: "Douzo yoroshiku onegaishimasu.",
  },
  {
    conversation_id: "conv103",
    translation: "こちらは田中さんです。",
    pronunciation: "Kochira wa Tanaka-san desu.",
  },
  {
    conversation_id: "conv104",
    translation: "お仕事は何ですか？",
    pronunciation: "Oshigoto wa nan desu ka?",
  },

  // Starting a New Job
  {
    conversation_id: "conv105",
    translation: "これからお世話になります。",
    pronunciation: "Kore kara osewa ni narimasu.",
  },
  {
    conversation_id: "conv106",
    translation: "これは私の名刺です。",
    pronunciation: "Kore wa watashi no meishi desu.",
  },
  {
    conversation_id: "conv107",
    translation: "頑張ります。",
    pronunciation: "Ganbarimasu.",
  },
  {
    conversation_id: "conv108",
    translation: "新人です。",
    pronunciation: "Shinjin desu.",
  },
  {
    conversation_id: "conv109",
    translation: "教えてください。",
    pronunciation: "Oshiete kudasai.",
  },
  {
    conversation_id: "conv110",
    translation: "私の机はどこですか？",
    pronunciation: "Watashi no tsukue wa doko desu ka?",
  },

  // Making a Purchase
  {
    conversation_id: "conv111",
    translation: "これをください。",
    pronunciation: "Kore o kudasai.",
  },
  {
    conversation_id: "conv112",
    translation: "これはいくらですか？",
    pronunciation: "Kore wa ikura desu ka?",
  },
  {
    conversation_id: "conv113",
    translation: "これを二つください。",
    pronunciation: "Kore o futatsu kudasai.",
  },
  {
    conversation_id: "conv114",
    translation: "もっと大きいのはありますか？",
    pronunciation: "Motto ookii no wa arimasu ka?",
  },
  {
    conversation_id: "conv115",
    translation: "あれをお願いします。",
    pronunciation: "Are o onegaishimasu.",
  },
  {
    conversation_id: "conv116",
    translation: "領収書をもらえますか？",
    pronunciation: "Ryoushuusho o moraemasu ka?",
  },

  // Asking Business Hours
  {
    conversation_id: "conv117",
    translation: "何時まで開いていますか？",
    pronunciation: "Nanji made aite imasu ka?",
  },
  {
    conversation_id: "conv118",
    translation: "何時に開きますか？",
    pronunciation: "Nanji ni akimasu ka?",
  },
  {
    conversation_id: "conv119",
    translation: "何時に閉まりますか？",
    pronunciation: "Nanji ni shimarimasu ka?",
  },
  {
    conversation_id: "conv120",
    translation: "日曜日は開いていますか？",
    pronunciation: "Nichiyoubi wa aite imasu ka?",
  },
  {
    conversation_id: "conv121",
    translation: "今開いていますか？",
    pronunciation: "Ima aite imasu ka?",
  },
  {
    conversation_id: "conv122",
    translation: "祝日は開いていますか？",
    pronunciation: "Shukujitsu wa aite imasu ka?",
  },

  // Confirming a Destination
  {
    conversation_id: "conv123",
    translation: "この電車は新宿へ行きますか？",
    pronunciation: "Kono densha wa Shinjuku e ikimasu ka?",
  },
  {
    conversation_id: "conv124",
    translation: "これは空港へ行きますか？",
    pronunciation: "Kore wa kuukou e ikimasu ka?",
  },
  {
    conversation_id: "conv125",
    translation: "京都行きはどのホームですか？",
    pronunciation: "Kyouto-yuki wa dono hoomu desu ka?",
  },
  {
    conversation_id: "conv126",
    translation: "そこまでどのくらいかかりますか？",
    pronunciation: "Soko made dono kurai kakarimasu ka?",
  },
  {
    conversation_id: "conv127",
    translation: "着いたら教えてください。",
    pronunciation: "Tsuitara oshiete kudasai.",
  },
  {
    conversation_id: "conv128",
    translation: "これは美術館行きのバスですか？",
    pronunciation: "Kore wa bijutsukan-yuki no basu desu ka?",
  },

  // JLPT N5
  {
    conversation_id: "conv129",
    translation: "私は学生です。",
    pronunciation: "Watashi wa gakusei desu.",
  },
  {
    conversation_id: "conv130",
    translation: "これは本です。",
    pronunciation: "Kore wa hon desu.",
  },
  {
    conversation_id: "conv131",
    translation: "これはペンではありません。",
    pronunciation: "Kore wa pen dewa arimasen.",
  },
  {
    conversation_id: "conv132",
    translation: "これは何ですか？",
    pronunciation: "Kore wa nan desu ka?",
  },
  {
    conversation_id: "conv133",
    translation: "今何時ですか？",
    pronunciation: "Ima nanji desu ka?",
  },
  {
    conversation_id: "conv134",
    translation: "毎日学校に行きます。",
    pronunciation: "Mainichi gakkou ni ikimasu.",
  },
  {
    conversation_id: "conv135",
    translation: "窓を開けてください。",
    pronunciation: "Mado o akete kudasai.",
  },
  {
    conversation_id: "conv136",
    translation: "ここに座ってもいいですか？",
    pronunciation: "Koko ni suwatte mo ii desu ka?",
  },
  {
    conversation_id: "conv137",
    translation: "日本に行きたいです。",
    pronunciation: "Nihon ni ikitai desu.",
  },
  {
    conversation_id: "conv138",
    translation: "机の上に本があります。",
    pronunciation: "Tsukue no ue ni hon ga arimasu.",
  },
  {
    conversation_id: "conv139",
    translation: "庭に猫がいます。",
    pronunciation: "Niwa ni neko ga imasu.",
  },
  {
    conversation_id: "conv140",
    translation: "私は音楽が好きです。",
    pronunciation: "Watashi wa ongaku ga suki desu.",
  },
  {
    conversation_id: "conv141",
    translation: "私は泳ぐことができます。",
    pronunciation: "Watashi wa oyogu koto ga dekimasu.",
  },
  {
    conversation_id: "conv142",
    translation: "東京は大阪より人が多いです。",
    pronunciation: "Toukyou wa Oosaka yori hito ga ooi desu.",
  },
  {
    conversation_id: "conv143",
    translation: "これからもっと勉強します。",
    pronunciation: "Kore kara motto benkyou shimasu.",
  },
  {
    conversation_id: "conv144",
    translation: "もう一度言ってください。",
    pronunciation: "Mou ichido itte kudasai.",
  },
  {
    conversation_id: "conv145",
    translation: "七時に朝ご飯を食べました。",
    pronunciation: "Shichi-ji ni asagohan o tabemashita.",
  },
  {
    conversation_id: "conv146",
    translation: "今、食べています。",
    pronunciation: "Ima, tabete imasu.",
  },
  {
    conversation_id: "conv147",
    translation: "ここでタバコを吸わないでください。",
    pronunciation: "Koko de tabako o suwanaide kudasai.",
  },
  {
    conversation_id: "conv148",
    translation: "これはいくらですか？",
    pronunciation: "Kore wa ikura desu ka?",
  },
  {
    conversation_id: "conv149",
    translation: "あの人は誰ですか？",
    pronunciation: "Ano hito wa dare desu ka?",
  },
  {
    conversation_id: "conv150",
    translation: "いつ日本に行きますか？",
    pronunciation: "Itsu Nihon ni ikimasu ka?",
  },
  {
    conversation_id: "conv151",
    translation: "飛行機で日本に来ました。",
    pronunciation: "Hikouki de Nihon ni kimashita.",
  },
  {
    conversation_id: "conv152",
    translation: "ここに三年住んでいます。",
    pronunciation: "Koko ni sannen sunde imasu.",
  },
  {
    conversation_id: "conv153",
    translation: "今日は寒いですね。",
    pronunciation: "Kyou wa samui desu ne.",
  },
  {
    conversation_id: "conv154",
    translation: "コーヒーはいかがですか？",
    pronunciation: "Koohii wa ikaga desu ka?",
  },
  {
    conversation_id: "conv155",
    translation: "会えるのを楽しみにしています。",
    pronunciation: "Aeru no o tanoshimi ni shite imasu.",
  },
  {
    conversation_id: "conv156",
    translation: "病気だったからです。",
    pronunciation: "Byouki datta kara desu.",
  },
  {
    conversation_id: "conv157",
    translation: "晩ご飯の後で勉強しました。",
    pronunciation: "Bangohan no ato de benkyou shimashita.",
  },
  {
    conversation_id: "conv158",
    translation: "趣味は写真を撮ることです。",
    pronunciation: "Shumi wa shashin o toru koto desu.",
  },
  {
    conversation_id: "conv159",
    translation: "勉強しに図書館へ行きます。",
    pronunciation: "Benkyou shini toshokan e ikimasu.",
  },
  {
    conversation_id: "conv160",
    translation: "水をください。",
    pronunciation: "Mizu o kudasai.",
  },
  {
    conversation_id: "conv161",
    translation: "学校にどうやって行きますか？",
    pronunciation: "Gakkou ni dou yatte ikimasu ka?",
  },
  {
    conversation_id: "conv162",
    translation: "この図書館には本がたくさんあります。",
    pronunciation: "Kono toshokan ni wa hon ga takusan arimasu.",
  },
  {
    conversation_id: "conv163",
    translation: "このりんごはあのりんごより安いです。",
    pronunciation: "Kono ringo wa ano ringo yori yasui desu.",
  },
  {
    conversation_id: "conv164",
    translation: "日本語が上手に話せません。",
    pronunciation: "Nihongo ga jouzu ni hanasemasen.",
  },
  {
    conversation_id: "conv165",
    translation: "日本語を教えてください。",
    pronunciation: "Nihongo o oshiete kudasai.",
  },
  {
    conversation_id: "conv166",
    translation: "いつも六時に起きます。",
    pronunciation: "Itsumo roku-ji ni okimasu.",
  },
  {
    conversation_id: "conv167",
    translation: "一緒に昼ご飯を食べましょう。",
    pronunciation: "Issho ni hirugohan o tabemashou.",
  },
  {
    conversation_id: "conv168",
    translation: "一緒に映画を見ませんか？",
    pronunciation: "Issho ni eiga o mimasen ka?",
  },
  {
    conversation_id: "conv169",
    translation: "お茶を飲みたいです。",
    pronunciation: "Ocha o nomitai desu.",
  },
  {
    conversation_id: "conv170",
    translation: "昨日公園に行きました。",
    pronunciation: "Kinou kouen ni ikimashita.",
  },
  {
    conversation_id: "conv171",
    translation: "ここに名前を書いてください。",
    pronunciation: "Koko ni namae o kaite kudasai.",
  },
  {
    conversation_id: "conv172",
    translation: "あの電車は京都へ行きます。",
    pronunciation: "Ano densha wa Kyouto e ikimasu.",
  },
  {
    conversation_id: "conv173",
    translation: "家族は何人ですか？",
    pronunciation: "Kazoku wa nannin desu ka?",
  },

  // JLPT N4
  {
    conversation_id: "conv174",
    translation: "食べてしまいました。",
    pronunciation: "Tabete shimaimashita.",
  },
  {
    conversation_id: "conv175",
    translation: "遅れるかもしれません。",
    pronunciation: "Okureru kamoshiremasen.",
  },
  {
    conversation_id: "conv176",
    translation: "仕事に行かないといけません。",
    pronunciation: "Shigoto ni ikanai to ikemasen.",
  },
  {
    conversation_id: "conv177",
    translation: "日本語を勉強することにしました。",
    pronunciation: "Nihongo o benkyou suru koto ni shimashita.",
  },
  {
    conversation_id: "conv178",
    translation: "おいしそうです。",
    pronunciation: "Oishisou desu.",
  },
  {
    conversation_id: "conv179",
    translation: "コーヒーを飲みながら本を読みます。",
    pronunciation: "Koohii o nominagara hon o yomimasu.",
  },
  {
    conversation_id: "conv180",
    translation: "食べすぎました。",
    pronunciation: "Tabesugimashita.",
  },
  {
    conversation_id: "conv181",
    translation: "雨が降れば行きません。",
    pronunciation: "Ame ga fureba ikimasen.",
  },
  {
    conversation_id: "conv182",
    translation: "私なら行きます。",
    pronunciation: "Watashi nara ikimasu.",
  },
  {
    conversation_id: "conv183",
    translation: "もっと勉強すればよかった。",
    pronunciation: "Motto benkyou sureba yokatta.",
  },
  {
    conversation_id: "conv184",
    translation: "忙しかったので、行けませんでした。",
    pronunciation: "Isogashikatta node, ikemasen deshita.",
  },
  {
    conversation_id: "conv185",
    translation: "雨が降りそうです。",
    pronunciation: "Ame ga furisou desu.",
  },
  {
    conversation_id: "conv186",
    translation: "わさびが食べられません。",
    pronunciation: "Wasabi ga taberaremasen.",
  },
  {
    conversation_id: "conv187",
    translation: "頑張れと言われました。",
    pronunciation: "Ganbare to iwaremashita.",
  },
  {
    conversation_id: "conv188",
    translation: "少し考えさせてください。",
    pronunciation: "Sukoshi kangaesasete kudasai.",
  },
  {
    conversation_id: "conv189",
    translation: "出かけるところです。",
    pronunciation: "Dekakeru tokoro desu.",
  },
  {
    conversation_id: "conv190",
    translation: "仕事が終わったばかりです。",
    pronunciation: "Shigoto ga owatta bakari desu.",
  },
  {
    conversation_id: "conv191",
    translation: "日本に行ったことがあります。",
    pronunciation: "Nihon ni itta koto ga arimasu.",
  },
  {
    conversation_id: "conv192",
    translation: "仕事の後でジムに行きます。",
    pronunciation: "Shigoto no ato de jimu ni ikimasu.",
  },
  {
    conversation_id: "conv193",
    translation: "その映画をまだ見ていません。",
    pronunciation: "Sono eiga o mada mite imasen.",
  },
  {
    conversation_id: "conv194",
    translation: "勉強しながら音楽を聴きました。",
    pronunciation: "Benkyou shinagara ongaku o kikimashita.",
  },
  {
    conversation_id: "conv195",
    translation: "友達にプレゼントをあげました。",
    pronunciation: "Tomodachi ni purezento o agemashita.",
  },
  {
    conversation_id: "conv196",
    translation: "友達がプレゼントをくれました。",
    pronunciation: "Tomodachi ga purezento o kuremashita.",
  },
  {
    conversation_id: "conv197",
    translation: "友達にプレゼントをもらいました。",
    pronunciation: "Tomodachi ni purezento o moraimashita.",
  },
  {
    conversation_id: "conv198",
    translation: "料理が上手です。",
    pronunciation: "Ryouri ga jouzu desu.",
  },
  {
    conversation_id: "conv199",
    translation: "歌うのが下手です。",
    pronunciation: "Utau no ga heta desu.",
  },
  {
    conversation_id: "conv200",
    translation: "寒くなりました。",
    pronunciation: "Samuku narimashita.",
  },
  {
    conversation_id: "conv201",
    translation: "新しいスマホがほしいです。",
    pronunciation: "Atarashii sumaho ga hoshii desu.",
  },
  {
    conversation_id: "conv202",
    translation: "本当かどうか分かりません。",
    pronunciation: "Hontou ka dou ka wakarimasen.",
  },
  {
    conversation_id: "conv203",
    translation: "ここから十分ぐらいです。",
    pronunciation: "Koko kara juppun gurai desu.",
  },
  {
    conversation_id: "conv204",
    translation: "早く起きるようにしています。",
    pronunciation: "Hayaku okiru you ni shite imasu.",
  },
  {
    conversation_id: "conv205",
    translation: "これを食べてみてください。",
    pronunciation: "Kore o tabete mite kudasai.",
  },
  {
    conversation_id: "conv206",
    translation: "この機械は使いやすいです。",
    pronunciation: "Kono kikai wa tsukaiyasui desu.",
  },
  {
    conversation_id: "conv207",
    translation: "この本は読みにくいです。",
    pronunciation: "Kono hon wa yominikui desu.",
  },
  {
    conversation_id: "conv208",
    translation: "京都に行って、お寺を見ました。",
    pronunciation: "Kyouto ni itte, otera o mimashita.",
  },
  {
    conversation_id: "conv209",
    translation: "出かける前に教えてください。",
    pronunciation: "Dekakeru mae ni oshiete kudasai.",
  },
  {
    conversation_id: "conv210",
    translation: "食べた後で、散歩に行きましょう。",
    pronunciation: "Tabeta ato de, sanpo ni ikimashou.",
  },
  {
    conversation_id: "conv211",
    translation: "切符を買わなければなりません。",
    pronunciation: "Kippu o kawanakereba narimasen.",
  },
  {
    conversation_id: "conv212",
    translation: "休みましょうか。",
    pronunciation: "Yasumimashou ka.",
  },
  {
    conversation_id: "conv213",
    translation: "大変でも、頑張ります。",
    pronunciation: "Taihen demo, ganbarimasu.",
  },

  // JLPT N3
  {
    conversation_id: "conv214",
    translation: "もっと勉強すべきです。",
    pronunciation: "Motto benkyou subeki desu.",
  },
  {
    conversation_id: "conv215",
    translation: "彼は先生らしいです。",
    pronunciation: "Kare wa sensei rashii desu.",
  },
  {
    conversation_id: "conv216",
    translation: "このりんごは甘っぽいです。",
    pronunciation: "Kono ringo wa amappoi desu.",
  },
  {
    conversation_id: "conv217",
    translation: "生きている限り、忘れません。",
    pronunciation: "Ikite iru kagiri, wasuremasen.",
  },
  {
    conversation_id: "conv218",
    translation: "読んでいるうちに暗くなりました。",
    pronunciation: "Yonde iru uchi ni kuraku narimashita.",
  },
  {
    conversation_id: "conv219",
    translation: "上司に叱られました。",
    pronunciation: "Joushi ni shikararemashita.",
  },
  {
    conversation_id: "conv220",
    translation: "息子に宿題をさせました。",
    pronunciation: "Musuko ni shukudai o sasemashita.",
  },
  {
    conversation_id: "conv221",
    translation: "待っているわけにはいきません。",
    pronunciation: "Matte iru wake ni wa ikimasen.",
  },
  {
    conversation_id: "conv222",
    translation: "謝らざるをえません。",
    pronunciation: "Ayamarazaru o emasen.",
  },
  {
    conversation_id: "conv223",
    translation: "来月大阪に行くつもりです。",
    pronunciation: "Raigetsu Oosaka ni iku tsumori desu.",
  },
  {
    conversation_id: "conv224",
    translation: "あなたのおかげで試験に合格しました。",
    pronunciation: "Anata no okage de shiken ni goukaku shimashita.",
  },
  {
    conversation_id: "conv225",
    translation: "雨のせいで試合が中止になりました。",
    pronunciation: "Ame no sei de shiai ga chuushi ni narimashita.",
  },
  {
    conversation_id: "conv226",
    translation: "家に着くとすぐにお茶を入れました。",
    pronunciation: "Ie ni tsuku to sugu ni ocha o iremashita.",
  },
  {
    conversation_id: "conv227",
    translation: "誰が来ても同じです。",
    pronunciation: "Dare ga kite mo onaji desu.",
  },
  {
    conversation_id: "conv228",
    translation: "寒いので、ヒーターをつけます。",
    pronunciation: "Samui node, hiitaa o tsukemasu.",
  },
  {
    conversation_id: "conv229",
    translation: "京都に何度も行ったことがあります。",
    pronunciation: "Kyouto ni nando mo itta koto ga arimasu.",
  },
  {
    conversation_id: "conv230",
    translation: "先生に漢字の書き方を教えてもらいました。",
    pronunciation: "Sensei ni kanji no kakikata o oshiete moraimashita.",
  },
  {
    conversation_id: "conv231",
    translation: "寝る前に本を読むようにしています。",
    pronunciation: "Neru mae ni hon o yomu you ni shite imasu.",
  },
  {
    conversation_id: "conv232",
    translation: "新しい店は人気だそうです。",
    pronunciation: "Atarashii mise wa ninki da sou desu.",
  },
  {
    conversation_id: "conv233",
    translation: "おいしいレストランみたいです。",
    pronunciation: "Oishii resutoran mitai desu.",
  },
  {
    conversation_id: "conv234",
    translation: "もっと早く言ってくれればよかったのに。",
    pronunciation: "Motto hayaku itte kurereba yokatta noni.",
  },
  {
    conversation_id: "conv235",
    translation: "誰にも言ってはいけません。",
    pronunciation: "Dare ni mo itte wa ikemasen.",
  },
  {
    conversation_id: "conv236",
    translation: "年齢にかかわらず大丈夫です。",
    pronunciation: "Nenrei ni kakawarazu daijoubu desu.",
  },
  {
    conversation_id: "conv237",
    translation: "暑さに耐えられません。",
    pronunciation: "Atsusa ni taeraremasen.",
  },
  {
    conversation_id: "conv238",
    translation: "彼は文句ばかり言っています。",
    pronunciation: "Kare wa monku bakari itte imasu.",
  },
  {
    conversation_id: "conv239",
    translation: "大きい犬が走っているのを見ました。",
    pronunciation: "Ookii inu ga hashitte iru no o mimashita.",
  },
  {
    conversation_id: "conv240",
    translation: "朝ご飯を食べずに家を出ます。",
    pronunciation: "Asagohan o tabezu ni ie o demasu.",
  },
  {
    conversation_id: "conv241",
    translation: "どんどん暑くなっています。",
    pronunciation: "Dondon atsuku natte imasu.",
  },
  {
    conversation_id: "conv242",
    translation: "着いたら知らせます。",
    pronunciation: "Tsuitara shirasemasu.",
  },
  {
    conversation_id: "conv243",
    translation: "晴れていたら、出かけられるのに。",
    pronunciation: "Harete itara, dekakerareru noni.",
  },
  {
    conversation_id: "conv244",
    translation: "雪が降ると思っていましたが、降りませんでした。",
    pronunciation: "Yuki ga furu to omotte imashita ga, furimasen deshita.",
  },
  {
    conversation_id: "conv245",
    translation: "出かける前にメールを送ってください。",
    pronunciation: "Dekakeru mae ni meeru o okutte kudasai.",
  },
  {
    conversation_id: "conv246",
    translation: "彼が疲れているのは当然です。",
    pronunciation: "Kare ga tsukarete iru no wa touzen desu.",
  },
  {
    conversation_id: "conv247",
    translation: "電車に乗り遅れるところでした。",
    pronunciation: "Densha ni noriokureru tokoro deshita.",
  },
  {
    conversation_id: "conv248",
    translation: "もう少しで事故にあうところでした。",
    pronunciation: "Mou sukoshi de jiko ni au tokoro deshita.",
  },
  {
    conversation_id: "conv249",
    translation: "この会社では残業が当たり前です。",
    pronunciation: "Kono kaisha de wa zangyou ga atarimae desu.",
  },
  {
    conversation_id: "conv250",
    translation: "頑張りますので、応援してください。",
    pronunciation: "Ganbarimasu node, ouen shite kudasai.",
  },
  {
    conversation_id: "conv251",
    translation: "窓を開けていただけませんか？",
    pronunciation: "Mado o akete itadakemasen ka?",
  },
  {
    conversation_id: "conv252",
    translation: "こちらでよろしいでしょうか？",
    pronunciation: "Kochira de yoroshii deshou ka?",
  },
  {
    conversation_id: "conv253",
    translation: "お会いできて光栄です。",
    pronunciation: "Oai dekite kouei desu.",
  },

  // Casual Slang
  {
    conversation_id: "conv254",
    translation: "やばい！",
    pronunciation: "Yabai!",
  },
  {
    conversation_id: "conv255",
    translation: "マジで？",
    pronunciation: "Maji de?",
  },
  {
    conversation_id: "conv256",
    translation: "ウケる。",
    pronunciation: "Ukeru.",
  },
  {
    conversation_id: "conv257",
    translation: "それな！",
    pronunciation: "Sore na!",
  },
  {
    conversation_id: "conv258",
    translation: "ウザい。",
    pronunciation: "Uzai.",
  },
  {
    conversation_id: "conv259",
    translation: "キモい。",
    pronunciation: "Kimoi.",
  },
  {
    conversation_id: "conv260",
    translation: "ムカつく。",
    pronunciation: "Mukatsuku.",
  },
  {
    conversation_id: "conv261",
    translation: "ガチ。",
    pronunciation: "Gachi.",
  },
  {
    conversation_id: "conv262",
    translation: "半端ない。",
    pronunciation: "Hanpa nai.",
  },
  {
    conversation_id: "conv263",
    translation: "微妙。",
    pronunciation: "Bimyou.",
  },
  {
    conversation_id: "conv264",
    translation: "ダサい。",
    pronunciation: "Dasai.",
  },
  {
    conversation_id: "conv265",
    translation: "えぐい。",
    pronunciation: "Egui.",
  },
  {
    conversation_id: "conv266",
    translation: "おっす！",
    pronunciation: "Ossu!",
  },
  {
    conversation_id: "conv267",
    translation: "わかんない。",
    pronunciation: "Wakannai.",
  },
  {
    conversation_id: "conv268",
    translation: "ワロタ。",
    pronunciation: "Warota.",
  },
  {
    conversation_id: "conv269",
    translation: "草（ｗｗｗ）。",
    pronunciation: "Kusa (www).",
  },
  {
    conversation_id: "conv270",
    translation: "エモい。",
    pronunciation: "Emoi.",
  },
  {
    conversation_id: "conv271",
    translation: "かわちぃ。",
    pronunciation: "Kawachii.",
  },
  {
    conversation_id: "conv272",
    translation: "めっちゃ。",
    pronunciation: "Meccha.",
  },
  {
    conversation_id: "conv273",
    translation: "あほ。",
    pronunciation: "Aho.",
  },
  {
    conversation_id: "conv274",
    translation: "おおきに。",
    pronunciation: "Ookini.",
  },
  {
    conversation_id: "conv275",
    translation: "ほんま？",
    pronunciation: "Honma?",
  },
  {
    conversation_id: "conv276",
    translation: "あかん。",
    pronunciation: "Akan.",
  },
  {
    conversation_id: "conv277",
    translation: "おもろい。",
    pronunciation: "Omoroi.",
  },
  {
    conversation_id: "conv278",
    translation: "ちゃうで！",
    pronunciation: "Chau de!",
  },
  {
    conversation_id: "conv279",
    translation: "スマホ。",
    pronunciation: "Sumaho.",
  },
  {
    conversation_id: "conv280",
    translation: "ググる。",
    pronunciation: "Guguru.",
  },
  {
    conversation_id: "conv281",
    translation: "ディスる。",
    pronunciation: "Disuru.",
  },
  {
    conversation_id: "conv282",
    translation: "サボる。",
    pronunciation: "Saboru.",
  },
  {
    conversation_id: "conv283",
    translation: "モテる。",
    pronunciation: "Moteru.",
  },
  {
    conversation_id: "conv284",
    translation: "ドンマイ。",
    pronunciation: "Donmai.",
  },
  {
    conversation_id: "conv285",
    translation: "チルる。",
    pronunciation: "Chiruru.",
  },
  {
    conversation_id: "conv286",
    translation: "ハマる。",
    pronunciation: "Hamaru.",
  },
  {
    conversation_id: "conv287",
    translation: "うそ！",
    pronunciation: "Uso!",
  },
  {
    conversation_id: "conv288",
    translation: "調子どう？",
    pronunciation: "Choushi dou?",
  },
  {
    conversation_id: "conv289",
    translation: "わりーね。",
    pronunciation: "Warii ne.",
  },
  {
    conversation_id: "conv290",
    translation: "おつ。",
    pronunciation: "Otsu.",
  },
  {
    conversation_id: "conv291",
    translation: "ノリがいい。",
    pronunciation: "Nori ga ii.",
  },
  {
    conversation_id: "conv292",
    translation: "ざっこ。",
    pronunciation: "Zakko.",
  },
  {
    conversation_id: "conv293",
    translation: "ナンパ。",
    pronunciation: "Nampa.",
  },
  {
    conversation_id: "conv294",
    translation: "パリピ。",
    pronunciation: "Paripi.",
  },
  {
    conversation_id: "conv295",
    translation: "オタク。",
    pronunciation: "Otaku.",
  },
  {
    conversation_id: "conv296",
    translation: "ちょ。",
    pronunciation: "Cho.",
  },
  {
    conversation_id: "conv297",
    translation: "すごい！",
    pronunciation: "Sugoi!",
  },
  {
    conversation_id: "conv298",
    translation: "一杯どう？",
    pronunciation: "Ippai dou?",
  },
  {
    conversation_id: "conv299",
    translation: "とりあえずビール。",
    pronunciation: "Toriaezu biiru.",
  },
  {
    conversation_id: "conv300",
    translation: "誰得？",
    pronunciation: "Daretoku?",
  },
  {
    conversation_id: "conv301",
    translation: "KY（空気読めない）。",
    pronunciation: "KY (Kuuki yomenai).",
  },
  {
    conversation_id: "conv302",
    translation: "なう。",
    pronunciation: "Nau.",
  },
  {
    conversation_id: "conv303",
    translation: "てへぺろ。",
    pronunciation: "Tehepero.",
  },

  // Rakuten guide additions
  {
    conversation_id: "conv304",
    translation: "英語のメニューはありますか？",
    pronunciation: "Eigo no menyuu wa arimasu ka?",
  },
  {
    conversation_id: "conv305",
    translation: "おすすめはありますか？",
    pronunciation: "Osusume wa arimasu ka?",
  },
  {
    conversation_id: "conv306",
    translation: "ここで降ります。",
    pronunciation: "Koko de orimasu.",
  },
  {
    conversation_id: "conv307",
    translation: "救急車を呼んでください。",
    pronunciation: "Kyuukyuusha o yonde kudasai.",
  },
  {
    conversation_id: "conv308",
    translation: "熱があります。",
    pronunciation: "Netsu ga arimasu.",
  },
  {
    conversation_id: "conv309",
    translation: "咳が出ます。",
    pronunciation: "Seki ga demasu.",
  },
  {
    conversation_id: "conv310",
    translation: "痛いです。",
    pronunciation: "Itai desu.",
  },
]
